Repository getredash/redash, pull requests merged in 2018-09, with the labels that each got.

#2786 Fix: queries with parameters with no value breaking the scheduler.
  redash/tasks/queries.py
Labels: needs-more-info

#2783 Receive communication error when Athena returns NaN value
  redash/query_runner/athena.py
  redash/utils/__init__.py
Labels: Backend, Bug

#2813 Sometimes widgets are getting zero height value
  client/app/components/dashboards/gridstack/index.js
Labels: Bug, Frontend

#2820 Minor code smell cleanup.
  redash/__init__.py
  redash/admin.py
  redash/cli/data_sources.py
  redash/destinations/__init__.py
  redash/handlers/authentication.py
  redash/handlers/base.py
  redash/handlers/favorites.py
  redash/handlers/organization.py
  redash/handlers/visualizations.py
  redash/models.py
  redash/query_runner/__init__.py
  redash/settings/__init__.py
  redash/settings/helpers.py
  redash/worker.py
  tests/__init__.py
  tests/handlers/test_favorites.py
  tests/handlers/test_query_results.py
  tests/models/test_users.py
  tests/test_cli.py
  tests/test_settings.py
Labels: Backend, Tech Debt, needs-more-info

#2800 Improved mobile design
  client/app/assets/less/redash/redash-newstyle.less
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.less
  client/app/pages/home/home.html
  client/app/pages/queries/query.html
Labels: needs-more-info

#2837 Fix: query embeds are broken.
  redash/serializers.py
Labels: needs-more-info

#2838 Fix: favorite button on homepage is not yellow.
  client/app/pages/home/home.html
Labels: needs-more-info

#2850 Docker based setup scripts
  .dockerignore
  setup/README.md
  setup/amazon_linux/README.md
  setup/amazon_linux/bootstrap.sh
  setup/amazon_linux/files/env
  setup/amazon_linux/files/nginx_redash_site
  setup/amazon_linux/files/postgres_apt.sh
  setup/amazon_linux/files/redash_supervisord_init
  setup/amazon_linux/files/redis.conf
  setup/amazon_linux/files/redis_init
  setup/amazon_linux/files/supervisord.conf
  setup/docker-compose.yml
  setup/setup.sh
  setup/ubuntu/README.md
  setup/ubuntu/bootstrap.sh
  setup/ubuntu/files/env
  setup/ubuntu/files/nginx_redash_site
  setup/ubuntu/files/supervisord.conf
Labels: Backend

#2859 Fix CircleCI setup for release branches.
  .circleci/config.yml
Labels: needs-more-info

#2852 Change placement (right/bottom) of chart legend depending on chart width
  client/app/visualizations/chart/plotly/index.js
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, UX, Visualizations: Chart

#2840 Improve counter visualization text scaling
  client/app/assets/less/inc/visualizations/counter-render.less
  client/app/visualizations/counter/counter-editor.html
  client/app/visualizations/counter/counter.html
  client/app/visualizations/counter/index.js
Labels: Frontend, Visualizations: Counter

#2637 React edit-in-place component
  client/app/assets/less/inc/edit-in-place.less
  client/app/components/EditInPlace.jsx
  client/app/components/edit-in-place.js
  client/app/components/groups/group-name.js
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
Labels: Frontend

#2877 Fix: wrong reference (EditInPlaceText -> EditInPlace)
  client/app/components/edit-in-place.js
Labels: needs-more-info

#2878 Fixed the fix.
  client/app/components/EditInPlace.jsx
  client/app/components/edit-in-place.js
Labels: needs-more-info
