Repository getredash/redash, pull requests merged in 2018-12, with the labels that each got.

#3162 Remove API permissions for users who have been disabled
  redash/authentication/__init__.py
  tests/test_authentication.py
Labels: needs-more-info

#3171 FIX: Reject empty query name
  client/app/components/EditInPlace.jsx
Labels: Bug, Frontend, Frontend: React

#3182 [Redshift] Fix: support for schema names with dots.
  redash/query_runner/pg.py
Labels: needs-more-info, review

#3183 Make refresh_queries less noisey in logs
  redash/tasks/queries.py
Labels: needs-more-info, review

#3180 Remove missing coverage from pytest terminal output
  .circleci/config.yml
  pytest.ini
Labels: review

#3186 Fix eslint issues on user.js
  client/app/services/user.js
Labels: review

#3187 Safely create_app in Celery code (try to fetch current_app first).
  redash/__init__.py
  redash/worker.py
Labels: review

#3194 Use multiple issue templates instead of a single one
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug_report.md
  .github/ISSUE_TEMPLATE/--anything_else.md
Labels: review

#3195 V6 release
  CHANGELOG.md
  package-lock.json
  package.json
  redash/__init__.py
Labels: needs-more-info, review

#3205 Widget: fix url parameters in query link
  client/app/services/query.js
Labels: Bug, Feature: Parameters, Frontend

#3174 Invalidate sessions after email or password change
  redash/authentication/__init__.py
  redash/handlers/users.py
  redash/models.py
  tests/__init__.py
  tests/handlers/test_users.py
  tests/test_handlers.py
Labels: review

#3211 Add test case
  tests/test_utils.py
Labels: review

#2503 [Athena] Fix: missing databases (apply pagination)
  redash/query_runner/athena.py
Labels: Backend, enhancement, review

#3206 Show Sort Y only when type is Heatmap
  client/app/visualizations/chart/chart-editor.html
Labels: review

#3216 Avoid exploding sql parse
  redash/handlers/query_results.py
Labels: in progress, review

#3092 Add dot behavior to autocomplete
  client/app/components/QueryEditor.jsx
  client/app/components/keywordBuilder.js
Labels: review

#3218 Fix: missing param fails for object values (like date range)
  redash/handlers/embed.py
  redash/handlers/query_results.py
  redash/utils/__init__.py
Labels: in progress, review

#3221 Use lower cased names for groups:
  tests/test_cli.py
Labels: in progress, review

#3220 Root folder cleanup
  .circleci/Dockerfile.cypress
  .circleci/docker-compose.cypress.yml
  old_migrations/0001_allow_delete_query.py
  old_migrations/0002_fix_timestamp_fields.py
  old_migrations/0003_update_data_source_config.py
  old_migrations/0004_allow_null_in_event_user.py
  old_migrations/0005_add_updated_at.py
  old_migrations/0006_queries_last_edit_by.py
  old_migrations/0007_add_schedule_to_queries.py
  old_migrations/0008_make_ds_name_unique.py
  old_migrations/0009_add_api_key_to_user.py
  old_migrations/0010_allow_deleting_datasources.py
  old_migrations/0010_create_alerts.py
  old_migrations/0011_migrate_bigquery_to_json.py
  old_migrations/0012_add_list_users_permission.py
  old_migrations/0013_update_counter_options.py
  old_migrations/0014_add_alert_rearm_seconds.py
  old_migrations/0014_migrate_existing_es_to_kibana.py
  old_migrations/0015_add_schedule_query_permission.py
  old_migrations/0016_add_alert_subscriber.py
  old_migrations/0016_drop_tables_from_group.py
  old_migrations/0017_add_organization.py
  old_migrations/0018_add_groups_refs.py
  old_migrations/0019_add_super_admin_permission.py
  old_migrations/0020_change_ds_name_to_non_uniqe.py
  old_migrations/0021_create_api_keys_table.py
  old_migrations/0022_add_new_permissions.py
  old_migrations/0023_add_notification_destination.py
  old_migrations/0023_make_sure_correct_group_type.py
  old_migrations/0024_add_options_to_query.py
  old_migrations/0025_add_query_snippets_table.py
  old_migrations/0026_add_access_control_tables.py
  old_migrations/0026_remove_query_trackers_redis_key.py
  old_migrations/0027_add_draft_toggle.py
Labels: in progress, review

#3228 Fix front-end compile error
  client/app/components/QueryEditor.jsx
Labels: review

#3232 Update webpack-build-notifier to dismiss warn
  package-lock.json
  package.json
Labels: in progress

#3225 Tests for find_missing_params
  tests/test_utils.py
Labels: review
