Repository getredash/redash, pull requests merged in 2018-05, with the labels that each got.

#2499 Design improvements
  client/app/assets/less/redash/redash-newstyle.less
  client/app/assets/less/server.less
  redash/templates/layouts/signed_out.html
Labels: Frontend, UX, enhancement

#2501 Improve dashboard refresh UX: show previous data while refreshing.
  client/app/components/dashboards/add-widget-dialog.js
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/services/widget.js
  redash/handlers/widgets.py
  tests/handlers/test_widgets.py
  webpack.config.js
Labels: Feature: Dashboards, Frontend, enhancement

#2472 Disable fork button for view_only user
  client/app/assets/less/inc/dropdown.less
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
Labels: UX

#2496 Fixes the order of columns in the schema browser when Redshift is used as a DataSource.
  redash/query_runner/pg.py
Labels: Backend, enhancement

#2520 Filter data sources in a data source input area
  client/app/pages/queries/query.html
Labels: Frontend, UX, enhancement

#2523 Frontend: fix boolean field with null value display as null.
  client/app/lib/value-format.js
Labels: Frontend

#2518 Design improvements
  client/app/assets/images/illustrations/alert.svg
  client/app/assets/images/illustrations/dashboard.svg
  client/app/assets/images/illustrations/query.svg
  client/app/assets/images/illustrations/readme.md
  client/app/assets/less/inc/toast.less
  client/app/assets/less/main.less
  client/app/assets/less/redash/query.less
  client/app/assets/less/server.less
  client/app/components/empty-state/empty-state.html
  client/app/components/empty-state/empty-state.js
  client/app/components/empty-state/empty-state.less
  client/app/components/groups/group-name.js
  client/app/pages/alerts-list/alerts-list.html
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/home/home.html
  client/app/pages/queries-list/queries-list.html
  client/app/pages/queries/query.html
  redash/templates/layouts/signed_out.html
Labels: Frontend, UX

#2511 Fixing signed_out.html template
  client/app/assets/less/server.less
  redash/templates/layouts/signed_out.html
Labels: Frontend

#2526 Fix pivot hide control in dashboards
  client/app/visualizations/pivot/index.js
Labels: Bug, Frontend, Visualizations

#2509 Show custom date format on settings page
  client/app/pages/settings/organization.html
  client/app/pages/settings/organization.js
  redash/handlers/authentication.py
Labels: Backend, Bug, Frontend

#2510 Display confirmation dialog when deleting a item
  client/app/pages/data-sources/show.js
  client/app/pages/destinations/show.js
  client/app/pages/query-snippets/edit.js
Labels: Frontend, UX, enhancement

#2536 Chart: formats for values, labels and tooltips
  client/app/lib/value-format.js
  client/app/services/query-result.js
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/utils.js
  client/app/visualizations/table/index.js
Labels: Frontend, Visualizations: Chart, enhancement
