Repository getredash/redash, pull requests merged in 2018-02, with the labels that each got.

#1692 Fixed monitoring metrics for Redis
  redash/monitor.py
Labels: enhancement

#2252 Empty states for Home, Dashboards, Queries and Alerts
  client/app/components/empty-state/empty-state.html
  client/app/components/empty-state/empty-state.js
  client/app/components/empty-state/empty-state.less
  client/app/pages/alerts-list/alerts-list.html
  client/app/pages/alerts-list/index.js
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard-list.js
  client/app/pages/home/home.html
  client/app/pages/queries-list/index.js
  client/app/pages/queries-list/queries-list.html
  redash/handlers/__init__.py
  redash/handlers/organization.py
Labels: Frontend, UX

#2338 Custom CSS based on column type
  client/app/components/dynamic-table/default-cell/template.html
  client/app/components/dynamic-table/dynamic-table.html
  client/app/components/dynamic-table/dynamic-table.less
  client/app/components/dynamic-table/json-cell/template.html
Labels: Frontend

#2337 Upgrade sqlparse to 0.2.4
  requirements.txt
  tests/handlers/test_queries.py
Labels: Backend

#2334 Add funnel visualization
  client/app/visualizations/funnel/funnel-editor.html
  client/app/visualizations/funnel/funnel.less
  client/app/visualizations/funnel/index.js
Labels: Frontend, UX
