Repository getredash/redash, pull requests merged in 2018-07, with the labels that each got.

#2638 Dashboard stops rendering when adding widget with empty query
  client/app/services/query.js
  client/app/visualizations/chart/plotly/utils.js
Labels: Bug, Feature: Dashboards, Frontend

#2583 Query header improvements on widgets
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.less
  client/app/components/queries/visualization-embed.html
  client/app/components/query-link.js
Labels: Frontend, UX, Visualizations

#2640 Keyboard shortcut to collapse query editor/schema browser
  client/app/directives/resizable-toggle.js
  client/app/pages/queries/query.html
  client/app/services/keyboard-shortcuts.js
Labels: Frontend, UX

#2584 keep query result pagination out of scroll
  client/app/components/dynamic-table/dynamic-table.less
Labels: Frontend, Visualizations

#2570 fixes query pagination alignment
  client/app/assets/less/redash/query.less
Labels: Frontend

#2514 Update value parsing for google spreadsheets source
  .gitignore
  redash/query_runner/google_spreadsheets.py
  tests/query_runner/test_google_spreadsheets.py
Labels: Backend

#2458 Get all tables in the BigQuery
  redash/query_runner/big_query.py
Labels: Backend

#2626 Show real status when loading cached query result
  client/app/pages/queries/query.html
  client/app/services/query-result.js
Labels: Frontend

#2697 Date/Time parameters: dynamic default value (current date/time)
  client/.babelrc
  client/app/components/DateInput.jsx
  client/app/components/DateTimeInput.jsx
  client/app/components/parameter-settings.html
  client/app/components/parameters.html
  client/app/services/query.js
  package-lock.json
  package.json
Labels: Feature: Parameters, Frontend, UX, enhancement

#2616 Pie chart: sectors colors
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, UX, Visualizations: Chart

#2513 Add location property to BigQuery data source settings
  redash/query_runner/big_query.py
Labels: enhancement

#2649 Add references to Airbnb's style guides in contribution guide.
  CONTRIBUTING.md
Labels: Documentation

#2482 add support ChatWork Alert Destination.
  client/app/assets/images/destinations/chatwork.png
  redash/destinations/chatwork.py
  redash/settings/__init__.py
Labels: Backend, enhancement
