Repository getredash/redash, pull requests merged in 2018-03, with the labels that each got.

#2354 Add a Redash extension system based on Python entrypoints.
  redash/__init__.py
  redash/extensions.py
Labels: enhancement

#2355 Use a paginator when iterating over glue tables
  redash/query_runner/athena.py
Labels: Backend

#2260 Extend the Prometheus query runner to support the range query
  redash/query_runner/prometheus.py
  redash/query_runner/python.py
  tests/query_runner/test_prometheus.py
Labels: enhancement

#2385 Add missing Cassandra and ScyllaDB images
  client/app/assets/images/db-logos/Cassandra.png
  client/app/assets/images/db-logos/scylla.png
Labels: Frontend, UX

#2412 Fix: Box plot hover
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, UX, Visualizations, enhancement

#2374 Choropleth visualization
  client/app/assets/less/inc/visualizations/map.less
  client/app/components/dynamic-table/default-cell/utils.js
  client/app/lib/value-format.js
  client/app/visualizations/chart/plotly/utils.js
  client/app/visualizations/choropleth/choropleth-editor.html
  client/app/visualizations/choropleth/choropleth.html
  client/app/visualizations/choropleth/countries.geo.json
  client/app/visualizations/choropleth/index.js
  client/app/visualizations/choropleth/utils.js
  client/app/visualizations/map/index.js
  client/app/visualizations/map/map-editor.html
  client/app/visualizations/map/map.html
  client/app/visualizations/table/index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: Frontend, Visualizations

#2376 Fix docker-entrypoint broke for other name than "postgres"
  bin/docker-entrypoint
Labels: Bug
