Repository getredash/redash, pull requests merged in 2018-06, with the labels that each got.

#2444 feat: show error if saml response cannot be parsed
  redash/authentication/saml_auth.py
Labels: Backend

#2549 Allow get_tables to see views and v10-style partitioned tables
  redash/query_runner/pg.py
Labels: Backend

#2578 Fix connection error when you run "create_tables"
  redash/cli/database.py
Labels: Backend

#2585 Show data only mode: allow to add and delete visualizations
  client/app/assets/less/redash/query.less
  client/app/pages/queries/query.html
  client/app/pages/queries/source-view.js
  client/app/pages/queries/view.js
Labels: Frontend, UX

#2580 add break-word wrap to add/edit text box on dashboard
  client/app/components/dashboards/add-widget-dialog.html
  client/app/components/dashboards/add-widget-dialog.js
  client/app/components/dashboards/add-widget-dialog.less
  client/app/components/dashboards/edit-text-box.html
  client/app/components/dashboards/widget.js
Labels: Frontend, UX

#2542 Closes #2541: x-axis improvements.
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/index.js
Labels: Frontend, Visualizations: Chart, enhancement

#2533 New datasource: Yandex Metrika&AppMetrika
  client/app/assets/images/db-logos/yandex_appmetrika.png
  client/app/assets/images/db-logos/yandex_metrika.png
  redash/query_runner/yandex_metrika.py
  redash/settings/__init__.py
Labels: Backend, enhancement

#2574 commit query result to db before evaluating alerts
  redash/tasks/queries.py
Labels: Backend

#2610 Fix export query results output file name
  client/app/services/query-result.js
Labels: Backend, enhancement
