Repository getredash/redash, pull requests merged in 2018-10, with the labels that each got.

#2883 Fix #2876 - Remove accidental query-result-link component from 'Add to dashboard link.'
  client/app/pages/queries/query.html
Labels: needs-more-info

#2894 Remove misplaced bracket.
  client/app/components/QueryEditor.jsx
Labels: needs-more-info

#2899 Add margin between format and autocomplete buttons
  client/app/components/QueryEditor.jsx
Labels: needs-more-info

#2909 MySQL: hide sys tables
  redash/query_runner/mysql.py
Labels: needs-more-info

#2946 Update snowflake_connector_python version
  requirements_all_ds.txt
Labels: needs-more-info

#2941 Bring back fix to Box plot hover.
  client/app/visualizations/chart/plotly/utils.js
Labels: needs-more-info

#2922 Query page layout improvements for small screens
  client/app/assets/less/redash/ant.less
  client/app/assets/less/redash/query.less
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/QueryEditor.jsx
  client/app/pages/queries/query.html
Labels: Frontend, UX

#2959 Add: option to auto reload widget data in shared dashboards.
  client/app/pages/dashboards/public-dashboard-page.js
Labels: needs-more-info

#2961 MongoDB: skip system collections when loading schema.
  redash/query_runner/mongodb.py
Labels: needs-more-info

#2960 Change: add timeout to destination requests.
  redash/destinations/chatwork.py
  redash/destinations/hipchat.py
  redash/destinations/mattermost.py
  redash/destinations/slack.py
  redash/destinations/webhook.py
Labels: needs-more-info

#2982 Table visualization: change default size to 25 and add more size options
  client/app/components/dynamic-table/index.js
  client/app/visualizations/table/index.js
Labels: needs-more-info

#2080 Add: Heatmap chart visualization by Plotly
  client/app/services/query-result.js
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/index.js
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, Visualizations

#2342 Apply query format options from settings
  redash/handlers/queries.py
  redash/settings/__init__.py
Labels: Backend

#3023 Plotly's toolbox covers part of the chart
  client/app/visualizations/chart/plotly/utils.js
Labels: Bug, Frontend, Visualizations: Chart

#3024 Charts lose responsive features after refreshing the dashboard
  client/app/visualizations/chart/plotly/index.js
Labels: Bug, Frontend, Visualizations: Chart
