Repository getredash/redash, pull requests merged in 2018-11, with the labels that each got.

#3035 Postgres query runner: handle NaN/Infinity values
  redash/query_runner/pg.py
Labels: Backend, Bug

#3051 Fix Docker Compose version number in Cypress config
  .circleci/docker-compose.cypress.yml
Labels: needs-more-info

#3054 Add Kylin logo
  client/app/assets/images/db-logos/kylin.png
  redash/query_runner/kylin.py
Labels: needs-more-info

#3058 Mustache: don't html-escape query parameters values
  client/app/services/query.js
  redash/handlers/embed.py
  redash/handlers/query_results.py
  redash/tasks/queries.py
  redash/utils/__init__.py
Labels: Backend, Bug, Frontend

#3061 Table visualization horizontal scrollbar should not be always visible
  client/app/components/dynamic-table/dynamic-table.less
Labels: needs-more-info

#3079 Always use basic autocomplete.
  client/app/components/QueryEditor.jsx
Labels: needs-more-info

#3094 Tags autocomplete: some tags not shown on search
  client/app/components/tags-control/modal-template.html
Labels: Bug, Frontend

#3046 Fix query page header
  client/app/assets/less/redash/query.less
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/tags-control/control-template.html
  client/app/components/tags-control/index.js
  client/app/components/tags-control/tags-control.less
  client/app/components/transclude-replace.js
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard.html
  client/app/pages/queries-list/queries-list.html
  client/app/pages/queries/query.html
Labels: Bug, Frontend, UX

#3112 Update changelog for v6.0.0-beta.
  CHANGELOG.md
Labels: needs-more-info

#3123 Remove (Beta) from Query Results query runner name
  redash/query_runner/query_results.py
Labels: needs-more-info

#3124 Support unicode in Postgres/Redshift schema
  redash/query_runner/pg.py
Labels: needs-more-info

#3138 Migrate all tags components to React
  client/app/assets/less/main.less
  client/app/assets/less/redash/ant.less
  client/app/assets/less/redash/tags-control.less
  client/app/components/tags-control/DashboardTagsControl.jsx
  client/app/components/tags-control/ModelTagsControl.jsx
  client/app/components/tags-control/QueryTagsControl.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/components/tags-control/TagsEditorModal.jsx
  client/app/components/tags-control/control-template.html
  client/app/components/tags-control/index.js
  client/app/components/tags-control/modal-template.html
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/pages/dashboards/dashboard.less
  client/app/pages/queries-list/queries-list.html
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
  package.json
  webpack.config.js
Labels: Frontend: React

#3142 When editing a dashboard title results in the visualizations being replaced by the loading markers
  client/app/pages/dashboards/dashboard.js
Labels: Bug, Frontend

#3144 Display only the first 8 characters of frontend version
  client/app/components/Footer.jsx
Labels: needs-more-info

#3145 take the first 8 characters for frontend version, not backend version
  client/app/components/Footer.jsx
Labels: needs-more-info
