Repository getredash/redash, pull requests merged in 2018-08, with the labels that each got.

#2761 Remove unnecessary init methods.
  redash/query_runner/__init__.py
  redash/query_runner/athena.py
  redash/query_runner/big_query.py
  redash/query_runner/cass.py
  redash/query_runner/clickhouse.py
  redash/query_runner/dynamodb_sql.py
  redash/query_runner/elasticsearch.py
  redash/query_runner/google_spreadsheets.py
  redash/query_runner/hive_ds.py
  redash/query_runner/impala_ds.py
  redash/query_runner/influx_db.py
  redash/query_runner/memsql_ds.py
  redash/query_runner/mssql.py
  redash/query_runner/mssql_odbc.py
  redash/query_runner/pg.py
  redash/query_runner/presto.py
  redash/query_runner/treasuredata.py
  redash/query_runner/vertica.py
  redash/query_runner/yandex_metrika.py
Labels: Backend

#2734 handling rows with "length" field with forOwn method
  client/app/services/query-result.js
Labels: Bug, Frontend, Visualizations

#2754 Widgets crumble when trying to move / resize a widget
  client/app/components/dashboards/gridstack/index.js
  client/app/visualizations/choropleth/utils.js
Labels: Bug, UX

#2759 Sort queries in descending order.
  client/app/pages/queries-list/index.js
Labels: Frontend

#2760 Add server-side sorting to dashboard list.
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard-list.js
  redash/handlers/dashboards.py
  redash/models.py
Labels: Backend, Frontend

#2769 Date/time params not working as global param
  client/app/components/parameters.js
  client/app/pages/dashboards/dashboard.js
  client/app/services/query.js
Labels: Bug
