Repository getredash/redash, pull requests merged in 2019-11, with the labels that each got.

#4276 New feature - Alert muting
  client/app/pages/alert/Alert.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/alert/components/AlertDestinations.less
  client/app/pages/alert/components/MenuButton.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/services/alert.js
  redash/handlers/alerts.py
  redash/handlers/api.py
  redash/models/__init__.py
  redash/tasks/alerts.py
  tests/tasks/test_alerts.py
Labels: Backend, Feature: Alerts, Frontend

#4301 Adjust RQ job priorities
  docker-compose.yml
  redash/cli/rq.py
  redash/tasks/general.py
Labels: Backend

#4306 RQ: periodically clear failed jobs
  redash/schedule.py
  redash/settings/__init__.py
  redash/tasks/__init__.py
  redash/tasks/general.py
Labels: Backend

#4323 Migrate Settings Screen to React
  client/app/assets/less/inc/base.less
  client/app/components/SettingsWrapper.jsx
  client/app/components/cards-list/CardsList.less
  client/app/components/settings-screen.html
  client/app/components/settings-screen.js
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/index.js
  client/app/services/settingsMenu.js
Labels: Frontend, Frontend: React

#4298 Auto-refresh admin status page
  client/app/pages/admin/Jobs.jsx
Labels: Frontend

#4302 Restarting rq-scheduler reschedules all periodics
  redash/cli/rq.py
  redash/schedule.py
  tests/test_schedule.py
Labels: Backend

#4299 Admin status page's current tab does not preserve
  client/app/components/admin/RQStatus.jsx
  client/app/pages/admin/Jobs.jsx
Labels: Frontend

#4270 Migrate Cohort visualization to React
  client/app/assets/less/inc/visualizations/cohort.less
  client/app/assets/less/main.less
  client/app/visualizations/cohort/Cornelius.jsx
  client/app/visualizations/cohort/Editor.jsx
  client/app/visualizations/cohort/Renderer.jsx
  client/app/visualizations/cohort/cohort-editor.html
  client/app/visualizations/cohort/cornelius.less
  client/app/visualizations/cohort/getOptions.js
  client/app/visualizations/cohort/index.js
  client/app/visualizations/cohort/prepareData.js
  client/app/visualizations/cohort/renderer.less
  client/cypress/integration/visualizations/cohort_spec.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, Visualizations

#4295 Fix: number based alerts evaluation isn't working
  redash/models/__init__.py
  tests/models/test_alerts.py
Labels: Backend, Bug, Feature: Alerts

#4313 Migrate Choropleth visualization to React
  client/app/assets/less/inc/visualizations/map.less
  client/app/lib/hooks/useMemoWithDeepCompare.js
  client/app/visualizations/choropleth/ColorPalette.js
  client/app/visualizations/choropleth/Editor/BoundsSettings.jsx
  client/app/visualizations/choropleth/Editor/ColorsSettings.jsx
  client/app/visualizations/choropleth/Editor/FormatSettings.jsx
  client/app/visualizations/choropleth/Editor/GeneralSettings.jsx
  client/app/visualizations/choropleth/Editor/editor.less
  client/app/visualizations/choropleth/Editor/index.jsx
  client/app/visualizations/choropleth/Editor/utils.js
  client/app/visualizations/choropleth/Renderer/Legend.jsx
  client/app/visualizations/choropleth/Renderer/index.jsx
  client/app/visualizations/choropleth/Renderer/initChoropleth.js
  client/app/visualizations/choropleth/Renderer/renderer.less
  client/app/visualizations/choropleth/Renderer/utils.js
  client/app/visualizations/choropleth/choropleth-editor.html
  client/app/visualizations/choropleth/choropleth.html
  client/app/visualizations/choropleth/getOptions.js
  client/app/visualizations/choropleth/index.js
  client/app/visualizations/choropleth/maps/countries.geo.json
  client/app/visualizations/choropleth/maps/japan.prefectures.geo.json
Labels: Frontend, Frontend: React, Visualizations

#4267 Migrate Funnel visualization to React
  client/app/visualizations/funnel/Editor/AppearanceSettings.jsx
  client/app/visualizations/funnel/Editor/GeneralSettings.jsx
  client/app/visualizations/funnel/Editor/index.jsx
  client/app/visualizations/funnel/Renderer/FunnelBar.jsx
  client/app/visualizations/funnel/Renderer/funnel-bar.less
  client/app/visualizations/funnel/Renderer/index.jsx
  client/app/visualizations/funnel/Renderer/index.less
  client/app/visualizations/funnel/Renderer/prepareData.js
  client/app/visualizations/funnel/funnel-editor.html
  client/app/visualizations/funnel/getOptions.js
  client/app/visualizations/funnel/index.js
  client/cypress/integration/visualizations/funnel_spec.js
  client/cypress/support/commands.js
Labels: Frontend, Frontend: React, Visualizations

#4358 Add some tests for Choropleth visualization
  client/app/components/ColorPicker/Input.jsx
  client/app/components/ColorPicker/index.jsx
  client/app/visualizations/choropleth/Editor/ColorsSettings.jsx
  client/app/visualizations/choropleth/Editor/FormatSettings.jsx
  client/app/visualizations/choropleth/Editor/GeneralSettings.jsx
  client/cypress/integration/visualizations/choropleth_spec.js
  client/cypress/support/commands.js
Labels: Frontend, Frontend: React, Visualizations

#4278 Migrate Map visualization to React
  client/app/components/ColorPicker/Label.jsx
  client/app/components/ColorPicker/Swatch.jsx
  client/app/components/ColorPicker/index.jsx
  client/app/components/ColorPicker/label.less
  client/app/components/ColorPicker/utils.js
  client/app/visualizations/choropleth/Editor/ColorsSettings.jsx
  client/app/visualizations/map/Editor/GeneralSettings.jsx
  client/app/visualizations/map/Editor/GroupsSettings.jsx
  client/app/visualizations/map/Editor/StyleSettings.jsx
  client/app/visualizations/map/Editor/index.jsx
  client/app/visualizations/map/Renderer.jsx
  client/app/visualizations/map/getOptions.js
  client/app/visualizations/map/index.js
  client/app/visualizations/map/initMap.js
  client/app/visualizations/map/map-editor.html
  client/app/visualizations/map/map.html
  client/app/visualizations/map/prepareData.js
  client/cypress/integration/visualizations/map_spec.js
Labels: Frontend, Frontend: React, Visualizations, Visualizations: Map

#4139 Migrate Chart visualization to React Part 2: Editor
  client/app/components/sortable/index.jsx
  client/app/visualizations/chart/Editor/AxisSettings.jsx
  client/app/visualizations/chart/Editor/ChartTypeSelect.jsx
  client/app/visualizations/chart/Editor/ColorsSettings.jsx
  client/app/visualizations/chart/Editor/ColorsSettings.test.js
  client/app/visualizations/chart/Editor/ColumnMappingSelect.jsx
  client/app/visualizations/chart/Editor/CustomChartSettings.jsx
  client/app/visualizations/chart/Editor/DataLabelsSettings.jsx
  client/app/visualizations/chart/Editor/DataLabelsSettings.test.js
  client/app/visualizations/chart/Editor/DefaultColorsSettings.jsx
  client/app/visualizations/chart/Editor/GeneralSettings.jsx
  client/app/visualizations/chart/Editor/GeneralSettings.test.js
  client/app/visualizations/chart/Editor/HeatmapColorsSettings.jsx
  client/app/visualizations/chart/Editor/PieColorsSettings.jsx
  client/app/visualizations/chart/Editor/SeriesSettings.jsx
  client/app/visualizations/chart/Editor/SeriesSettings.test.js
  client/app/visualizations/chart/Editor/XAxisSettings.jsx
  client/app/visualizations/chart/Editor/XAxisSettings.test.js
  client/app/visualizations/chart/Editor/YAxisSettings.jsx
  client/app/visualizations/chart/Editor/YAxisSettings.test.js
  client/app/visualizations/chart/Editor/__snapshots__/ColorsSettings.test.js.snap
  client/app/visualizations/chart/Editor/__snapshots__/DataLabelsSettings.test.js.snap
  client/app/visualizations/chart/Editor/__snapshots__/GeneralSettings.test.js.snap
  client/app/visualizations/chart/Editor/__snapshots__/SeriesSettings.test.js.snap
  client/app/visualizations/chart/Editor/__snapshots__/XAxisSettings.test.js.snap
  client/app/visualizations/chart/Editor/__snapshots__/YAxisSettings.test.js.snap
  client/app/visualizations/chart/Editor/editor.less
  client/app/visualizations/chart/Editor/index.jsx
  client/app/visualizations/chart/Editor/index.test.js
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/getOptions.js
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/prepareDefaultData.js
Labels: Frontend, Frontend: React, Visualizations, Visualizations: Chart

#4380 Remove unused npm dependencies
  client/app/config/index.js
  client/app/lib/sortable.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4388 Hide deprecated visualizations from query editor
  client/app/components/ColorPicker/index.jsx
  client/app/visualizations/EditVisualizationDialog.jsx
  client/cypress/integration/visualizations/box_plot_spec.js
Labels: Frontend, Visualizations

#4389 Table visualization: accept timestamp for date/time columns
  client/app/lib/value-format.js
Labels: Frontend, Visualizations, Visualizations: Table

#4396 Avoid purging jobs which have already been deleted
  redash/tasks/general.py
Labels: Backend

#4394 Table visualization with column named "children" renders +/- buttons
  client/app/visualizations/table/Renderer.jsx
  client/app/visualizations/table/utils.js
Labels: Bug, Frontend, Visualizations, Visualizations: Table

#4372 Amazon CloudWatch query runners
  client/app/assets/images/db-logos/cloudwatch.png
  client/app/assets/images/db-logos/cloudwatch_insights.png
  redash/query_runner/cloudwatch.py
  redash/query_runner/cloudwatch_insights.py
  redash/settings/__init__.py
Labels: Backend

#4311 RQ: simplify logging of jobs
  redash/cli/rq.py
  redash/settings/__init__.py
  redash/worker.py
Labels: Backend
