Repository getredash/redash, pull requests merged in 2019-03, with the labels that each got.

#3502 Fix verification_email endpoint when in MULTI_ORG mode
  client/app/pages/home/index.js
Labels: PR: unreviewed, in progress

#3518 Fix eslint error on AlertsList
  client/app/pages/alerts/AlertsList.jsx
Labels: PR: reviewed-approved, in progress

#3519 Show invitation link if email server not setup
  client/app/pages/users/CreateUser.jsx
  redash/handlers/users.py
  tests/handlers/test_users.py
Labels: PR: unreviewed, in progress

#3520 Show invitation link if email server not setup
  redash/handlers/users.py
Labels: PR: unreviewed, in progress

#3522 Moved widget and dashboard save logic out of dialog
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
Labels: PR: reviewed-approved, in progress

#3524 Migrated AddTextboxDialog to AntD
  client/app/components/dashboards/AddTextboxDialog.jsx
  client/app/components/dashboards/AddTextboxDialog.less
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/pages/dashboards/dashboard.js
Labels: PR: unreviewed, in progress

#3506 Migrate User Pages to React
  client/app/components/EmailSettingsWarning.jsx
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/email-settings-warning/index.js
  client/app/components/error-messages.js
  client/app/components/proptypes.js
  client/app/components/users/CreateUserDialog.jsx
  client/app/components/users/UserEdit.jsx
  client/app/components/users/UserShow.jsx
  client/app/components/users/UserShow.test.js
  client/app/pages/alert/alert.html
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/index.js
  client/app/pages/users/new.html
  client/app/pages/users/new.js
  client/app/pages/users/show.html
  client/app/pages/users/show.js
  client/app/services/user.js
  redash/handlers/users.py
  tests/handlers/test_users.py
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, in progress

#3517 Added UTC display to scheduler dialog
  client/app/components/queries/ScheduleDialog.css
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  package.json
Labels: PR: unreviewed, in progress

#3529 Refine New user modal
  client/app/lib/utils.js
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/index.js
Labels: Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3525 Add Hangouts Chat as alert destination
  client/app/assets/images/destinations/hangouts_chat.png
  redash/destinations/hangoutschat.py
  redash/settings/__init__.py
Labels: Backend, Feature: API, PR: reviewed-approved, PR: unreviewed, in progress

#3532 Remove Flask-Admin. Fix #3438.
  redash/__init__.py
  redash/admin.py
  requirements.txt
Labels: Backend, PR: unreviewed, in progress

#3534 Make the "celery" queue the default instead of "schema" to stay backward-compatible.
  redash/settings/__init__.py
  redash/tasks/queries.py
  tests/tasks/test_refresh_schemas.py
Labels: Backend, PR: unreviewed, in progress

#3537 Remove duplicate column information for late-binding views
  redash/query_runner/pg.py
Labels: PR: unreviewed, in progress

#3533 Remove docker-compose.production.yml in favor of setup/docker-compose.yml.
  docker-compose.production.yml
  docker-compose.yml
Labels: Backend, PR: unreviewed, in progress

#3528 Param fix
  client/app/components/EditParameterSettingsDialog.jsx
Labels: Frontend, PR: unreviewed, UX, in progress

#3543 Pin pymapd version to 0.7.1
  requirements_all_ds.txt
Labels: Backend, in progress

#3545 Fix long tag labels breaking table layout
  client/app/assets/less/redash/redash-newstyle.less
Labels: in progress

#3540 Fix list pages
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/FavoritesControl.jsx
  client/app/components/groups/DeleteGroupButton.jsx
  client/app/lib/utils.js
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/users/UsersList.jsx
Labels: Bug, Frontend, in progress

#3549 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#3552 Fix: order dashboard favorites
  redash/handlers/api.py
  redash/handlers/dashboards.py
  redash/handlers/favorites.py
  redash/handlers/queries.py
Labels: Backend, in progress

#3548 Add: Docker entrypoint to do Celery healthchecks.
  bin/docker-entrypoint
Labels: Backend, in progress

#3550 Snowflake: add support for regions and enable by default
  redash/query_runner/snowflake.py
  redash/settings/__init__.py
  requirements_all_ds.txt
Labels: Backend, in progress

#3405 Upgrade jest & babel
  client/.babelrc
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  package-lock.json
  package.json
Labels: in progress

#3559 Download Query Result links: use query name for downloaded filename
  client/app/components/queries/query-results-link.js
  redash/handlers/query_results.py
  redash/utils/__init__.py
Labels: Bug, in progress

#3057 New Celery/Queries Execution Status API
  client/app/assets/less/ant.less
  client/app/components/admin/CeleryStatus.jsx
  client/app/pages/admin/outdated-queries/outdated-queries.html
  client/app/pages/admin/status/status.html
  client/app/pages/admin/tasks/index.js
  client/app/pages/admin/tasks/tasks.html
  migrations/versions/e5c7a4e2df4d_remove_query_tracker_keys.py
  redash/handlers/admin.py
  redash/monitor.py
  redash/tasks/__init__.py
  redash/tasks/queries.py
  redash/worker.py
  tests/tasks/test_queries.py
Labels: in progress

#3561 npm audit fixes
  package-lock.json
  package.json
  webpack.config.js
Labels: in progress

#3564 Handle errors on Group Members, Group Data Sources and User Profile pages
  client/app/components/items-list/ItemsList.jsx
  client/app/components/items-list/classes/ItemsSource.js
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/users/UserProfile.jsx
Labels: Bug, Frontend, in progress

#3567 Update Amazon Elasticsearch Service image
  client/app/assets/images/db-logos/aws_es.png
Labels: in progress

#3563 Convert all dropdown values to strings to support parameter lookup
  client/app/components/QueryBasedParameterInput.jsx
  redash/utils/parameterized_query.py
  tests/utils/test_parameterized_query.py
Labels: in progress

#3557 Prevent blank edit-in-place value
  client/app/components/EditInPlace.jsx
Labels: in progress

#3573 Fix webpack config to work with symlinks
  webpack.config.js
Labels: in progress

#3574 Append "UTC" to timestamp on embeds (in print view)
  client/app/components/queries/visualization-embed.html
Labels: in progress

#3580 Fork query does not fork tables but instead adds default table
  redash/models/__init__.py
  tests/models/test_queries.py
Labels: Backend, Bug, Visualizations, Visualizations: Table, in progress

#2947 Add SAML scheme override env var
  redash/authentication/saml_auth.py
  redash/settings/__init__.py
Labels: in progress

#3578 👋 goodbye, similar-code false positives.
  .codeclimate.yml
Labels: in progress

#3582 Fix for parameter mapping bug #3581
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
Labels: in progress

#3291 Schema Viewer Drawer
  client/app/assets/less/ant.less
  client/app/assets/less/inc/schema-browser.less
  client/app/components/proptypes.js
  client/app/components/queries/SchemaData.jsx
  client/app/components/queries/schema-browser.html
  client/app/components/queries/schema-browser.js
  migrations/versions/280daa582976_.py
  redash/handlers/data_sources.py
  redash/models/__init__.py
  redash/query_runner/__init__.py
  redash/query_runner/athena.py
  redash/query_runner/mysql.py
  redash/query_runner/pg.py
  redash/query_runner/presto.py
  redash/settings/__init__.py
  redash/tasks/__init__.py
  redash/tasks/queries.py
  redash/worker.py
  tests/factories.py
  tests/models/test_data_sources.py
  tests/query_runner/test_get_schema_format.py
  tests/tasks/test_queries.py
  tests/tasks/test_refresh_schemas.py
  tests/test_cli.py
Labels: in progress

#3479 Added alt+enter key binding
  client/app/pages/queries/view.js
Labels: in progress

#3565 Cypress test - dashboard create/archive
  .circleci/Dockerfile.cypress
  client/app/components/app-header/app-header.html
  client/app/components/dashboards/edit-dashboard-dialog.html
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/dashboard.html
  cypress/integration/dashboard/dashboard_spec.js
Labels: in progress

#3585 Revert "Schema Viewer Drawer (#3291)"
  client/app/assets/less/ant.less
  client/app/assets/less/inc/schema-browser.less
  client/app/components/proptypes.js
  client/app/components/queries/SchemaData.jsx
  client/app/components/queries/schema-browser.html
  client/app/components/queries/schema-browser.js
  migrations/versions/280daa582976_.py
  redash/handlers/data_sources.py
  redash/models/__init__.py
  redash/query_runner/__init__.py
  redash/query_runner/athena.py
  redash/query_runner/mysql.py
  redash/query_runner/pg.py
  redash/query_runner/presto.py
  redash/settings/__init__.py
  redash/tasks/__init__.py
  redash/tasks/queries.py
  redash/worker.py
  tests/factories.py
  tests/models/test_data_sources.py
  tests/query_runner/test_get_schema_format.py
  tests/tasks/test_queries.py
  tests/tasks/test_refresh_schemas.py
  tests/test_cli.py
Labels: in progress

#3586 Widget title link not updated when parameter value changes
  client/app/components/query-link.js
Labels: Bug, Frontend, in progress

#3587 Revert "Add SAML scheme override env var"
  redash/authentication/saml_auth.py
  redash/settings/__init__.py
Labels: in progress

#3588 update to latest stable version
  setup/docker-compose.yml
Labels: in progress

#3577 Reuse handlers base require_fields
  redash/handlers/data_sources.py
  redash/handlers/destinations.py
Labels: Backend, in progress

#3594 Update user list when an user is created
  client/app/pages/users/UsersList.jsx
Labels: in progress

#3596 Fix: accept integer values in dropdowns.
  redash/utils/parameterized_query.py
  tests/utils/test_parameterized_query.py
Labels: Backend, Feature: Parameters, in progress

#3589 Textbox testing - add, remove, edit
  client/app/pages/dashboards/dashboard.html
  cypress/integration/dashboard/dashboard_spec.js
Labels: in progress

#3595 Update v7 CHANGELOG and version
  CHANGELOG.md
  package-lock.json
  package.json
  redash/__init__.py
Labels: in progress

#3600 Fix: make sure that only the top level node_modules directory is excluded
  .circleci/pack
  bin/pack
Labels: in progress

#3603 Remove node_modules before creating tarball
  .circleci/config.yml
  .circleci/pack
Labels: in progress

#3544 Nest query ACL to dropdowns
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/services/query.js
  redash/handlers/api.py
  redash/handlers/queries.py
  redash/handlers/query_results.py
  redash/models/__init__.py
  redash/models/parameterized_query.py
  redash/serializers.py
  tests/handlers/test_queries.py
  tests/handlers/test_query_results.py
  tests/models/test_parameterized_query.py
Labels: in progress

#3618 Query Results fails to use query which has double quotes in column names
  redash/query_runner/query_results.py
  tests/query_runner/test_query_results.py
Labels: Backend, in progress

#3590 Widget tests - add, remove, auto height
  client/app/components/QuerySelector.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  cypress/integration/dashboard/dashboard_spec.js
Labels: Frontend, Visualizations: Table, in progress

#3616 Added a skipped test for issue #3202
  cypress/integration/dashboard/dashboard_spec.js
Labels: in progress

#3624 Fix a DeprecationWarning about the Flask.static_path parameter.
  redash/__init__.py
Labels: in progress

#3566 Move cypress to client folder
  .circleci/Dockerfile.cypress
  .circleci/config.yml
  .gitignore
  client/cypress/cypress.js
  client/cypress/integration/dashboard/dashboard_spec.js
  client/cypress/integration/data-source/create_data_source_spec.js
  client/cypress/integration/data-source/edit_data_source_spec.js
  client/cypress/integration/destination/create_destination_spec.js
  client/cypress/integration/group/edit_group_spec.js
  client/cypress/integration/group/group_list_spec.js
  client/cypress/integration/query/create_query_spec.js
  client/cypress/integration/query/search_query_spec.js
  client/cypress/integration/settings/organization_settings_spec.js
  client/cypress/integration/user/edit_profile_spec.js
  client/cypress/integration/user/login_spec.js
  client/cypress/integration/user/logout_spec.js
  client/cypress/integration/user/user_list_spec.js
  client/cypress/plugins/index.js
  client/cypress/seed-data.js
  client/cypress/support/commands.js
  client/cypress/support/index.js
  cypress.json
  package.json
Labels: in progress

#3610 Replace toastr with Ant Notification
  client/app/assets/less/ant.less
  client/app/assets/less/main.less
  client/app/components/QueryEditor.jsx
  client/app/components/QuerySelector.jsx
  client/app/components/SelectItemsDialog.jsx
  client/app/components/alerts/alert-subscriptions/index.js
  client/app/components/dashboards/AddTextboxDialog.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dashboards/widget.js
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/groups/DeleteGroupButton.jsx
  client/app/components/permissions-editor/index.js
  client/app/components/users/ChangePasswordDialog.jsx
  client/app/config/index.js
  client/app/index.js
  client/app/pages/alert/index.js
  client/app/pages/dashboards/ShareDashboardDialog.jsx
  client/app/pages/dashboards/dashboard.js
  client/app/pages/data-sources/show.js
  client/app/pages/destinations/list.js
  client/app/pages/destinations/show.js
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/home/index.js
  client/app/pages/queries/add-to-dashboard.js
  client/app/pages/queries/view.js
  client/app/pages/query-snippets/edit.js
  client/app/pages/settings/organization.js
  client/app/pages/users/UsersList.jsx
  client/app/services/ng.js
  client/app/services/notification.js
  client/app/services/offline-listener.js
  client/app/services/user.js
  client/app/visualizations/edit-visualization-dialog.js
  package-lock.json
  package.json
Labels: in progress

#3622 Add env var to skip Flask rate limits
  .circleci/docker-compose.cypress.yml
  docker-compose.yml
  redash/settings/__init__.py
  tests/__init__.py
Labels: in progress

#3598 Widget drag tests
  client/cypress/integration/dashboard/dashboard_spec.js
Labels: Feature: Dashboards, Frontend, in progress

#3568 Migrate Admin pages to React
  client/app/components/admin/CeleryStatus.jsx
  client/app/components/admin/Layout.jsx
  client/app/components/admin/StatusBlock.jsx
  client/app/components/admin/layout.less
  client/app/components/groups/DetailsPageSidebar.jsx
  client/app/components/items-list/ItemsList.jsx
  client/app/components/items-list/classes/ItemsSource.js
  client/app/components/items-list/components/Sidebar.jsx
  client/app/config/antd-spinner.jsx
  client/app/config/index.js
  client/app/pages/admin/OutdatedQueries.jsx
  client/app/pages/admin/SystemStatus.jsx
  client/app/pages/admin/Tasks.jsx
  client/app/pages/admin/outdated-queries/index.js
  client/app/pages/admin/outdated-queries/outdated-queries.html
  client/app/pages/admin/status/index.js
  client/app/pages/admin/status/status.html
  client/app/pages/admin/system-status.less
  client/app/pages/admin/tasks/index.js
  client/app/pages/admin/tasks/tasks.html
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/users/UsersList.jsx
Labels: Frontend, Frontend: React, in progress

#3626 Fix a few more inconsistencies when loading and dumping JSON.
  redash/authentication/jwt_auth.py
  redash/monitor.py
  redash/query_runner/db2.py
  redash/query_runner/kylin.py
  redash/query_runner/rockset.py
  redash/query_runner/uptycs.py
Labels: in progress

#3404 Use flask-talisman for handling backend response headers
  redash/__init__.py
  redash/authentication/__init__.py
  redash/authentication/account.py
  redash/extensions.py
  redash/handlers/__init__.py
  redash/handlers/dashboards.py
  redash/handlers/embed.py
  redash/handlers/static.py
  redash/metrics/request.py
  redash/models/__init__.py
  redash/security.py
  redash/settings/__init__.py
  requirements.txt
  setup/generate_key.sh
  setup/setup.sh
  tests/handlers/test_data_sources.py
  tests/handlers/test_embed.py
  tests/handlers/test_favorites.py
  tests/handlers/test_queries.py
  tests/handlers/test_settings.py
Labels: in progress

#3530 Render LDAP and remote auth login links correctly when multi org mode is enabled.
  redash/authentication/ldap_auth.py
  redash/templates/login.html
  tests/test_handlers.py
Labels: in progress

#3609 Browser support config
  client/.babelrc
  client/.eslintrc.js
  client/app/index.html
  client/app/multi_org.html
  client/app/unsupported.html
  package-lock.json
  package.json
  webpack.config.js
Labels: in progress

#3153 Add phoenix query runner.
  client/app/assets/images/db-logos/phoenix.png
  redash/query_runner/phoenix.py
  redash/settings/__init__.py
  requirements_all_ds.txt
Labels: in progress

#3499 Fail query task properly even if error message is empty
  redash/tasks/queries.py
Labels: in progress

#3613 Fix email shows as unverified when no email server is configured
  redash/handlers/authentication.py
  redash/handlers/users.py
  redash/settings/__init__.py
  tests/handlers/test_users.py
Labels: in progress

#3592 allowing to specify a custom work group for AWS Athena queries
  redash/query_runner/athena.py
  requirements_all_ds.txt
Labels: in progress

#3599 Show accessible tables only in New Query view for PostgreSQL
  redash/query_runner/pg.py
Labels: in progress

#3625 Fix Celery worker --max-tasks-per-child for Celery 4.x.
  bin/docker-entrypoint
Labels: in progress

#3450 Manage user groups in UserEdit
  client/app/assets/less/ant.less
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/proptypes.js
  client/app/components/users/UserEdit.jsx
  client/app/components/users/UserShow.jsx
  client/app/components/users/UserShow.test.js
  client/app/components/users/__snapshots__/UserShow.test.js.snap
  client/app/services/group.js
  client/app/services/user.js
  client/cypress/integration/user/edit_profile_spec.js
  redash/handlers/users.py
  tests/handlers/test_users.py
Labels: Frontend, Frontend: React, in progress

#3480 Treat repeated BigQuery fields as arrays
  redash/query_runner/big_query.py
Labels: in progress

#3620 Widget resize tests
  client/app/components/dashboards/widget.html
  client/app/components/parameters.html
  client/app/pages/dashboards/dashboard.html
  client/cypress/integration/dashboard/dashboard_spec.js
Labels: in progress

#3470 Migrate Data Sources and Alert Destinations pages to React
  client/app/assets/less/ant.less
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/CreateSourceDialog.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/PreviewCard.jsx
  client/app/components/cards-list/CardsList.jsx
  client/app/components/cards-list/CardsList.less
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/dynamic-form/dynamicFormHelper.js
  client/app/components/proptypes.js
  client/app/components/type-picker.html
  client/app/components/type-picker.js
  client/app/components/users/CreateUserDialog.jsx
  client/app/components/users/UserEdit.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/data-sources/list.html
  client/app/pages/data-sources/list.js
  client/app/pages/data-sources/show.html
  client/app/pages/data-sources/show.js
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/destinations/list.html
  client/app/pages/destinations/list.js
  client/app/pages/destinations/show.html
  client/app/pages/destinations/show.js
  client/app/services/data-source.js
  client/app/services/destination.js
  client/app/services/policy/DefaultPolicy.js
  client/cypress/integration/data-source/create_data_source_spec.js
  client/cypress/integration/destination/create_destination_spec.js
Labels: Frontend, Frontend: React, in progress

#3611 Change has_access and require_access signatures
  redash/handlers/alerts.py
  redash/handlers/data_sources.py
  redash/handlers/favorites.py
  redash/handlers/queries.py
  redash/handlers/query_results.py
  redash/handlers/widgets.py
  redash/models/parameterized_query.py
  redash/permissions.py
  redash/query_runner/query_results.py
  redash/serializers.py
Labels: in progress

#3648 Migrate Timer component to React; update TimeAgo component
  client/app/components/TimeAgo.jsx
  client/app/components/Timer.jsx
  client/app/components/dashboards/widget.html
  client/app/components/rd-timer.js
  client/app/lib/hooks/useForceUpdate.js
  client/app/pages/queries/query.html
Labels: Frontend, Frontend: React
