Repository getredash/redash, pull requests merged in 2019-02, with the labels that each got.

#3389 Fix Cypress E2E failing in CI
  .circleci/Dockerfile.cypress
  package.json
Labels: PR: reviewed-approved, in progress

#3385 Migrate "time ago" components to React
  client/app/components/DateInput.jsx
  client/app/components/DateRangeInput.jsx
  client/app/components/DateTimeInput.jsx
  client/app/components/DateTimeRangeInput.jsx
  client/app/components/TimeAgo.jsx
  client/app/components/proptypes.js
  client/app/components/rd-time-ago.js
  client/app/config/index.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: unreviewed, in progress

#3391 fix lint error - getDerivedStateFromProps should be placed after state
  client/app/components/TimeAgo.jsx
Labels: PR: unreviewed, in progress, needs-more-info

#2888 Add archived queries section to queries list.
  client/app/assets/less/redash/redash-newstyle.less
  client/app/lib/list-ctrl.js
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard-list.js
  client/app/pages/queries-list/index.js
  client/app/pages/queries-list/queries-list.html
  client/app/pages/users/list.js
  client/app/services/query.js
  redash/handlers/api.py
  redash/handlers/organization.py
  redash/handlers/queries.py
  redash/models/__init__.py
  tests/handlers/test_queries.py
Labels: PR: unreviewed, in progress

#3376 Make the logic around schedule['until'] easier to read
  redash/models/__init__.py
Labels: PR: unreviewed, in progress

#3387 [Widget Params] Migrated edit params + new widget dialog to Ant Modal
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/hoc/ModalOpener.jsx
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
Labels: Frontend: React, PR: reviewed-approved, PR: unreviewed, in progress

#3367 Use textless endpoint for pristine queries
  client/app/pages/queries/view.js
  client/app/services/query-result.js
  client/app/services/query.js
Labels: PR: reviewed-approved, in progress

#3398 Fix: Selected item in dropdown unreadable
  client/app/assets/less/redash/redash-newstyle.less
Labels: PR: unreviewed, in progress

#3390 Added pre-push hook
  package-lock.json
  package.json
Labels: PR: unreviewed, in progress

#3332 [Widget Params] Switched parameter list to table style (all parts)
  client/app/assets/less/ant.less
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterMappingInput.less
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/services/query.js
Labels: PR: unreviewed, in progress, typescript-ftw

#3395 Add YAML support in QueryEditor
  client/app/components/QueryEditor.jsx
Labels: Frontend, PR: unreviewed, in progress

#3381 Migrate Dashboards/Queries/Users list pages to React
  client/app/assets/less/ant.less
  client/app/assets/less/inc/ant-variables.less
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/BigMessage.jsx
  client/app/components/DynamicComponent.jsx
  client/app/components/FavoritesControl.jsx
  client/app/components/NoTaggedObjectsFound.jsx
  client/app/components/TagsList.jsx
  client/app/components/items-list/LiveItemsList.jsx
  client/app/components/items-list/components/EmptyState.jsx
  client/app/components/items-list/components/ItemsTable.jsx
  client/app/components/items-list/components/LoadingState.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/components/queries/SchedulePhrase.jsx
  client/app/config/index.js
  client/app/filters/datetime.js
  client/app/lib/list-ctrl.js
  client/app/lib/pagination/live-paginator.js
  client/app/lib/utils.js
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardListEmptyState.jsx
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/dashboard-list.js
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries-list/QueriesListEmptyState.jsx
  client/app/pages/queries-list/index.js
  client/app/pages/queries-list/queries-list.html
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/list.html
  client/app/pages/users/list.js
  client/app/services/navigateTo.js
  client/app/services/ng.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, PR: unreviewed, in progress

#3397 Fix: cohorts get stuck when passing strings instead of numbers.
  client/app/visualizations/cohort/index.js
Labels: Frontend, PR: reviewed-approved, PR: unreviewed, Visualizations, in progress

#3402 Fixes to Query list page
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries-list/QueriesListEmptyState.jsx
Labels: Bug, Frontend, PR: unreviewed, in progress

#3150 Coerce to moment when 'datetime' selected by user.
  client/app/visualizations/chart/plotly/utils.js
Labels: PR: reviewed-approved, in progress

#3412 Work around a resizing issue.
  client/app/components/QueryEditor.jsx
Labels: PR: unreviewed, in progress

#3400 Show active and pending users separately (for admins)
  client/app/components/items-list/LiveItemsList.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/pages/users/UsersList.jsx
  redash/handlers/users.py
  redash/models/users.py
  tests/handlers/test_users.py
Labels: Backend, Frontend, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, in progress

#3414 Fix: “Add TextBox” dialog not opening
  client/app/pages/dashboards/dashboard.html
Labels: PR: merged

#3413 [Widget Params] Title edit fixes
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterMappingInput.less
  client/app/services/dashboard.js
Labels: PR: unreviewed, in progress

#3407 Refine dialog wrapper and use it for all existing dialogs
  client/app/components/DialogWrapper.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dashboards/widget.js
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  client/app/components/tags-control/EditTagsDialog.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/config/index.js
  client/app/hoc/ModalOpener.jsx
  client/app/pages/dashboards/dashboard.js
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: unreviewed, in progress

#3416 Use Ant's Button component on users list page
  client/app/assets/less/ant.less
  client/app/assets/less/inc/ant-variables.less
  client/app/pages/users/UsersList.jsx
Labels: Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3337 Unify query based dropdown population
  client/app/components/QueryBasedParameterInput.jsx
  client/app/services/query.js
  redash/handlers/api.py
  redash/handlers/query_results.py
  redash/utils/parameterized_query.py
  tests/handlers/test_query_results.py
  tests/utils/test_parameterized_query.py
Labels: PR: unreviewed, in progress

#3366 Modal style adjustment
  client/app/assets/less/ant.less
  client/app/components/tags-control/EditTagsDialog.jsx
Labels: PR: unreviewed, in progress

#3403 Handle InterruptException in Athena query runnner
  redash/query_runner/athena.py
Labels: PR: unreviewed, in progress

#3418 Upgrade Sentry SDK
  redash/__init__.py
  redash/utils/sentry.py
  redash/worker.py
  requirements.txt
Labels: PR: unreviewed, in progress

#3422 Fix: show query result footer only when there is a query result.
  client/app/pages/queries/query.html
Labels: PR: reviewed-approved, in progress

#3421 Fix: saving a new query removes reference to last query result
  client/app/pages/queries/view.js
  redash/handlers/queries.py
Labels: PR: unreviewed, in progress

#3417 Alternative implementation of dashboard param title editing
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterMappingInput.less
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/services/dashboard.js
Labels: Frontend, PR: unreviewed, UX, in progress

#3419 Enable remote debugging with ptvsd
  bin/docker-entrypoint
  docker-compose.yml
  redash/__init__.py
  requirements_dev.txt
Labels: PR: unreviewed, in progress

#3424 Converted Share modal to Ant
  client/app/assets/less/ant.less
  client/app/components/InputWithCopy.jsx
  client/app/pages/dashboards/ShareDashboardDialog.jsx
  client/app/pages/dashboards/dashboard.js
  client/app/pages/dashboards/share-dashboard.html
Labels: Frontend, Frontend: React, PR: reviewed-approved

#3426 Notifications randomly shown with visible page or not shown with inactive page
  client/app/services/notifications.js
Labels: Bug, Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3427 Query Parameters: don't save urlPrefix
  client/app/services/query.js
Labels: Bug, Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3410 Pre-commit hook to run on modified files only
  package-lock.json
  package.json
Labels: PR: unreviewed, in progress

#3428 [Widget Params] Updated help url and tooltip
  client/app/components/ParameterMappingInput.jsx
Labels: PR: unreviewed, in progress

#3430 send ip and user id to sentry
  redash/utils/sentry.py
Labels: PR: unreviewed, in progress, needs-more-info

#3429 Version update time ⏰
  package.json
  redash/__init__.py
Labels: PR: unreviewed, in progress

#3431 HelpTrigger
  client/app/components/ParameterMappingInput.jsx
  client/app/pages/dashboards/ShareDashboardDialog.jsx
  client/app/services/HelpTrigger.jsx
Labels: PR: unreviewed, in progress

#3310 Raise the upper limit of MAX_JSON_SIZE
  client/app/components/dynamic-table/json-cell/index.js
  redash/handlers/authentication.py
  redash/settings/__init__.py
Labels: PR: unreviewed, in progress

#3354 React version of UserEdit
  .circleci/config.yml
  client/app/assets/less/ant.less
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/proptypes.js
  client/app/components/users/ChangePasswordDialog.jsx
  client/app/components/users/UserEdit.jsx
  client/app/components/users/UserShow.jsx
  client/app/components/users/UserShow.test.js
  client/app/components/users/__snapshots__/UserShow.test.js.snap
  client/app/pages/users/show.html
  client/app/pages/users/show.js
  client/app/services/user.js
  cypress/integration/percy/page_screenshots.js
  cypress/integration/user/edit_profile_spec.js
  cypress/support/commands.js
Labels: PR: unreviewed, in progress

#3439 Sharing disabled if dashboard has query params
  client/app/pages/dashboards/ShareDashboardDialog.jsx
  client/app/pages/dashboards/dashboard.js
Labels: PR: reviewed-approved, in progress

#3423 Fix: remove widgets when deleting a visualization.
  redash/models/__init__.py
  tests/handlers/test_visualizations.py
Labels: PR: merged

#3449 Improve InvalidParameterError message
  redash/utils/parameterized_query.py
Labels: PR: unreviewed, in progress

#2970 Change: encrypt data source options. 🔓
  migrations/versions/98af61feea92_add_encrypted_options_to_data_sources.py
  redash/models/__init__.py
  redash/models/types.py
  redash/settings/__init__.py
  redash/utils/configuration.py
Labels: PR: reviewed-approved, in progress

#3436 HelpTrigger to open in drawer
  client/app/assets/less/ant.less
  client/app/services/HelpTrigger.jsx
  client/app/services/HelpTrigger.less
Labels: PR: unreviewed, in progress

#3446 Add support for Amazon ES service with IAM authentication
  client/app/assets/images/db-logos/aws_es.png
  redash/query_runner/amazon_elasticsearch.py
  redash/query_runner/elasticsearch.py
  redash/settings/__init__.py
  requirements_all_ds.txt
Labels: in progress

#3447 Fix: ScheduleDialog won't render for "30 days" interval with no time value
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
Labels: Bug, Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3457 HelpTrigger in header
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/HelpTrigger.jsx
  client/app/components/HelpTrigger.less
  client/app/components/ParameterMappingInput.jsx
  client/app/components/app-header/app-header.html
  client/app/pages/dashboards/ShareDashboardDialog.jsx
Labels: PR: unreviewed, in progress

#3415 Refine ItemsList base component (previously LiveItemsList)
  .circleci/Dockerfile.cypress
  client/app/components/items-list/ItemsList.jsx
  client/app/components/items-list/LiveItemsList.jsx
  client/app/components/items-list/classes/ItemsFetcher.js
  client/app/components/items-list/classes/ItemsSource.js
  client/app/components/items-list/classes/Paginator.js
  client/app/components/items-list/classes/Sorter.js
  client/app/components/items-list/classes/StateStorage.js
  client/app/lib/pagination/index.js
  client/app/lib/pagination/live-paginator.js
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/users/UsersList.jsx
  package.json
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: unreviewed, in progress

#3440 Fixes to Percy
  client/app/components/TimeAgo.jsx
  client/app/components/type-picker.html
  client/app/pages/data-sources/show.html
  client/app/pages/groups/list.html
  client/app/pages/groups/show.html
  client/app/pages/settings/organization.html
  cypress/cypress.js
  cypress/integration/data-source/create_data_source_spec.js
  cypress/integration/data-source/edit_data_source_spec.js
  cypress/integration/destination/create_destination_spec.js
  cypress/integration/group/edit_group_spec.js
  cypress/integration/group/group_list_spec.js
  cypress/integration/percy/page_screenshots.js
  cypress/integration/settings/organization_settings_spec.js
  cypress/integration/user/edit_profile_spec.js
  cypress/integration/user/user_list_spec.js
Labels: PR: reviewed-approved

#3458 Version data - footer -> header menu
  client/app/components/Footer.jsx
  client/app/components/Footer.test.js
  client/app/components/__snapshots__/Footer.test.js.snap
  client/app/components/app-header/app-header.css
  client/app/components/app-header/app-header.html
  client/app/components/app-header/index.js
  redash/templates/footer.html
Labels: PR: reviewed-approved, in progress

#3445 Fix: widget oblivious to updated parameter values
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dashboards/widget.js
Labels: PR: unreviewed, in progress

#3463 Fix: timedelta values were not JSON serialized properly
  redash/utils/__init__.py
Labels: PR: reviewed-approved, in progress

#3460 Remove options NullPool does not support
  redash/models/base.py
Labels: Backend, PR: reviewed-approved, PR: unreviewed, in progress

#3452 Fail on superfluous parameters
  redash/utils/parameterized_query.py
  tests/utils/test_parameterized_query.py
Labels: PR: unreviewed, review

#3462 Fix: when max_age is None the handler fails
  redash/handlers/query_results.py
Labels: Backend, PR: reviewed-approved, PR: unreviewed, in progress

#3464 Fix: JS Map needs a set call rather than assignment
  client/app/components/DynamicComponent.jsx
Labels: Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3461 Fix: ParameterizedQuery: support for upper cases column names.
  redash/utils/parameterized_query.py
  tests/utils/test_parameterized_query.py
Labels: Backend, PR: reviewed-approved, PR: unreviewed, in progress

#3469 Fix strict slashes for email verification
  client/app/pages/home/index.js
  redash/handlers/authentication.py
Labels: PR: unreviewed, in progress

#3468 Fix e-mail verification for multi org setups
  redash/handlers/authentication.py
  redash/templates/verify.html
Labels: PR: unreviewed, in progress

#3472 Help trigger dynamic component
  client/app/components/HelpTrigger.jsx
Labels: PR: reviewed-approved, in progress

#3474 Provide default value for .pop to avoid KeyError exception
  redash/models/base.py
Labels: PR: unreviewed, in progress, needs-more-info

#3459 monitor "schemas" queue to run refresh_schema
  .circleci/docker-compose.cypress.yml
  bin/docker-entrypoint
  docker-compose.production.yml
  docker-compose.yml
  setup/docker-compose.yml
Labels: PR: unreviewed, in progress

#3476 Fix some flex layout issue
  client/app/components/HelpTrigger.jsx
  client/app/components/HelpTrigger.less
Labels: PR: unreviewed, in progress

#3477 Fix max-age issues on textless endpoint
  client/app/services/query.js
  redash/handlers/query_results.py
Labels: PR: unreviewed, in progress

#3113 Cleaner approach for _is_collection_a_view
  redash/query_runner/mongodb.py
Labels: PR: unreviewed, PR: waiting-for-feedback, in progress

#3411 Migrate Group List and Details pages to React
  client/app/assets/less/ant.less
  client/app/assets/less/inc/base.less
  client/app/assets/less/inc/generics.less
  client/app/components/PreviewCard.jsx
  client/app/components/SelectItemsDialog.jsx
  client/app/components/groups/CreateGroupDialog.jsx
  client/app/components/groups/DeleteGroupButton.jsx
  client/app/components/groups/DetailsPageSidebar.jsx
  client/app/components/groups/GroupName.jsx
  client/app/components/groups/ListItemAddon.jsx
  client/app/components/groups/edit-group-dialog.html
  client/app/components/groups/edit-group-dialog.js
  client/app/components/groups/group-name.js
  client/app/components/items-list/ItemsList.jsx
  client/app/components/items-list/classes/ItemsFetcher.js
  client/app/components/items-list/classes/ItemsSource.js
  client/app/components/items-list/components/ItemsTable.jsx
  client/app/lib/utils.js
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/groups/data-sources.html
  client/app/pages/groups/data-sources.js
  client/app/pages/groups/list.html
  client/app/pages/groups/list.js
  client/app/pages/groups/show.html
  client/app/pages/groups/show.js
  client/app/pages/users/UsersList.jsx
  client/app/services/group.js
  client/app/services/navigateTo.js
  client/app/services/ng.js
  cypress/integration/group/edit_group_spec.js
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, in progress

#3482 Improve list pages layout
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/groups/DetailsPageSidebar.jsx
  client/app/components/layouts/ContentWithSidebar.jsx
  client/app/components/layouts/content-with-sidebar.less
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/users/UsersList.jsx
Labels: Frontend, PR: reviewed-approved, PR: unreviewed, Tech Debt, in progress

#3483 fix broken link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved, in progress

#3484 Use series name as pie chart label
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, PR: unreviewed, Visualizations: Chart, in progress

#3485 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#3489 Fix update logo
  client/app/assets/images/destinations/slack.png
Labels: PR: unreviewed, in progress

#3471 Fix prometheus query runner: get_schema and query range
  redash/query_runner/prometheus.py
Labels: PR: reviewed-approved, in progress

#3490 Pin SQLAlchemy-Utils version
  requirements.txt
Labels: in progress

#3442 Add custom JSON encoder for PostgreSQL
  redash/query_runner/pg.py
Labels: Backend, PR: unreviewed, in progress

#3465 Make sure Flask app created in Celery's worker process
  redash/__init__.py
  redash/worker.py
Labels: Backend, PR: unreviewed, in progress

#3492 Update Percy token
  .circleci/config.yml
Labels: PR: unreviewed, in progress

#3487 Fix DynamicForm ignoring default value for checkboxes
  client/app/components/dynamic-form/dynamicFormHelper.js
Labels: Frontend, Frontend: React, PR: unreviewed, in progress

#3383 Be more permissive when parameters are safe
  client/app/pages/queries/view.js
  redash/handlers/queries.py
  redash/handlers/query_results.py
  redash/models/__init__.py
  redash/serializers.py
  redash/utils/parameterized_query.py
  tests/handlers/test_query_results.py
  tests/utils/test_parameterized_query.py
Labels: PR: unreviewed, review

#3500 Fix: users can't use password reset form
  redash/handlers/authentication.py
Labels: PR: unreviewed, in progress

#3333 adding gevent worker in requirements.txt, adding some gunicorn config…
  requirements.txt
Labels: PR: unreviewed, PR: waiting-for-feedback, in progress

#3504 Verify address when users change their e-mail
  redash/handlers/users.py
  tests/handlers/test_users.py
Labels: PR: reviewed-approved, in progress

#3005 Support AWS IAM profile for Amazon Elasticsearch
  redash/query_runner/amazon_elasticsearch.py
  requirements_all_ds.txt
Labels: PR: reviewed-approved, in progress

#2776 LDAP Authentication. Create two envars REDASH_LDAP_USE_SSL and REDASH_LDAP_AUTH_BIND
  redash/authentication/ldap_auth.py
  redash/settings/__init__.py
Labels: PR: unreviewed

#3505 Migrate Alerts List Page to React
  client/app/assets/less/redash/redash-newstyle.less
  client/app/pages/alerts-list/alerts-list.html
  client/app/pages/alerts-list/index.js
  client/app/pages/alerts/AlertsList.jsx
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#3494 Added <QuerySelector /> component
  client/.eslintrc.js
  client/app/components/QuerySelector.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/lib/highlight.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, PR: unreviewed, in progress

#3511 CircleCI build improvements
  .circleci/config.yml
  .circleci/docker_build
  .circleci/docker_tag
Labels: PR: unreviewed, in progress

#3501 QuerySelector in Alert page
  client/app/assets/less/redash/tags-control.less
  client/app/components/QuerySelector.jsx
  client/app/pages/alert/alert.html
  client/app/pages/alert/index.js
Labels: PR: unreviewed, in progress

#3488 Migrated query edit/add param dialog to React/AntD/Hooks
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/EditParameterSettingsDialog.jsx
  client/app/components/parameter-settings.html
  client/app/components/parameters.html
  client/app/components/parameters.js
  client/app/pages/queries/query.html
  client/app/pages/queries/source-view.js
Labels: Frontend, Frontend: React, PR: unreviewed, in progress

#3510 Fixed navbar responsiveness
  client/app/assets/less/inc/navbar.less
  client/app/assets/less/redash/query.less
  client/app/assets/less/redash/redash-newstyle.less
Labels: PR: unreviewed, in progress
