Repository getredash/redash, pull requests merged in 2019-05, with the labels that each got.

#3619 Support for Presto password
  redash/query_runner/presto.py
Labels: in progress

#3756 Fix: pie chart not rendering when series doesn't exist in options.
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, Visualizations

#3762 Add direction option in Pie Chart
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/utils.js
Labels: Frontend, Visualizations, enhancement

#3759 Fix: dashboard filters collects all options too
  client/app/services/dashboard.js
Labels: Frontend, UX

#3154 Choropleth customize
  client/app/visualizations/choropleth/choropleth-editor.html
  client/app/visualizations/choropleth/index.js
  client/app/visualizations/choropleth/japan.prefectures.geo.json
  client/app/visualizations/choropleth/utils.js
Labels: Frontend, Visualizations

#3728 Migrate Organization Settings to React
  client/app/components/HelpTrigger.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/settings/organization.html
  client/app/pages/settings/organization.js
  client/app/services/organizationSettings.js
  client/cypress/integration/settings/organization_settings_spec.js
Labels: Frontend: React

#3794 Visualization rendering getting cut in editor on first load
  client/app/directives/resize-event.js
Labels: Bug, Frontend, Visualizations

#3800 Edit parameter mapping: error when trying to change mapping type to Static; cannot change static value
  client/app/components/ParameterMappingInput.jsx
Labels: Bug, Frontend

#3799 Plotly modebar appears above modals
  client/app/assets/less/ant.less
  client/app/components/dashboards/AddWidgetDialog.jsx
Labels: Bug, Frontend

#3722 Dashboard grid React migration #1
  client/app/components/dashboards/AutoHeightController.js
  client/app/components/dashboards/DashboardGrid.jsx
  client/app/components/dashboards/dashboard-grid.less
  client/app/components/dashboards/gridstack/gridstack.js
  client/app/components/dashboards/gridstack/gridstack.less
  client/app/components/dashboards/gridstack/index.js
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/components/dashboards/widget.less
  client/app/config/dashboard-grid-options.js
  client/app/config/index.js
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/pages/dashboards/dashboard.less
  client/app/pages/dashboards/public-dashboard-page.html
  client/app/pages/dashboards/public-dashboard-page.js
  client/app/services/dashboard.js
  client/app/services/widget.js
  client/cypress/integration/dashboard/dashboard_spec.js
  package-lock.json
  package.json
Labels: Feature: Dashboards, Frontend: React

#3569 Decouple extensions from Flask app.
  .circleci/config.yml
  Dockerfile
  bin/bundle-extensions
  redash/extensions.py
  redash/worker.py
  requirements.txt
  requirements_bundles.txt
Labels: Backend, in progress

#3826 Migrate CreateDashboardDialog to React
  client/app/assets/less/ant.less
  client/app/components/DynamicComponent.jsx
  client/app/components/app-header/index.js
  client/app/components/dashboards/CreateDashboardDialog.jsx
  client/app/components/dashboards/edit-dashboard-dialog.html
  client/app/components/dashboards/edit-dashboard-dialog.js
  client/app/components/empty-state/EmptyState.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/cypress/integration/dashboard/dashboard_spec.js
Labels: Frontend, Frontend: React

#3853 Fix initialization of dashboard-level parameters
  client/app/services/dashboard.js
Labels: Bug, Feature: Dashboards, Feature: Parameters, Frontend

#3852 Disable filter which does not have values
  client/app/components/Filters.jsx
Labels: Bug, Frontend

#3864 Use more specific CSS for public dashboard page to avoid conflicts with other components
  client/app/pages/dashboards/dashboard.less
Labels: Bug, Feature: Dashboards, Frontend
