Repository getredash/redash, pull requests merged in 2019-09, with the labels that each got.

#4119 display data source icon in query editor
  client/app/pages/queries/query.html
Labels: Frontend

#4114 Feature (Redshift): option to set query group for adhoc/scheduled queries
  redash/query_runner/pg.py
  redash/tasks/queries.py
Labels: Backend, enhancement

#4113 Move annotation logic into Query Runner
  redash/query_runner/__init__.py
  redash/query_runner/athena.py
  redash/query_runner/azure_kusto.py
  redash/query_runner/big_query.py
  redash/query_runner/couchbase.py
  redash/query_runner/dgraph.py
  redash/query_runner/dynamodb_sql.py
  redash/query_runner/elasticsearch.py
  redash/query_runner/google_analytics.py
  redash/query_runner/google_spreadsheets.py
  redash/query_runner/graphite.py
  redash/query_runner/hive_ds.py
  redash/query_runner/influx_db.py
  redash/query_runner/jql.py
  redash/query_runner/json_ds.py
  redash/query_runner/memsql_ds.py
  redash/query_runner/mongodb.py
  redash/query_runner/mssql.py
  redash/query_runner/mssql_odbc.py
  redash/query_runner/pg.py
  redash/query_runner/prometheus.py
  redash/query_runner/python.py
  redash/query_runner/qubole.py
  redash/query_runner/query_results.py
  redash/query_runner/salesforce.py
  redash/query_runner/script.py
  redash/query_runner/treasuredata.py
  redash/query_runner/uptycs.py
  redash/query_runner/url.py
  redash/query_runner/yandex_metrica.py
  redash/tasks/queries.py
Labels: Backend

#4106 Migrate Counter visualization to React
  client/app/assets/less/inc/visualizations/counter-render.less
  client/app/assets/less/main.less
  client/app/pages/dashboards/dashboard.less
  client/app/visualizations/counter/Editor.jsx
  client/app/visualizations/counter/Renderer.jsx
  client/app/visualizations/counter/counter-editor.html
  client/app/visualizations/counter/counter.html
  client/app/visualizations/counter/index.js
  client/app/visualizations/counter/render.less
  client/app/visualizations/counter/utils.js
  client/cypress/integration/visualizations/counter_spec.js
Labels: Frontend, Frontend: React, Visualizations, Visualizations: Counter

#4071 Allow the user to decide how to handle null values in charts
  client/app/lib/value-format.js
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/fixtures/getChartData/multiple-series-grouped.json
  client/app/visualizations/chart/fixtures/getChartData/multiple-series-multiple-y.json
  client/app/visualizations/chart/fixtures/getChartData/multiple-series-sorted.json
  client/app/visualizations/chart/fixtures/getChartData/single-series.json
  client/app/visualizations/chart/getChartData.js
  client/app/visualizations/chart/getChartData.test.js
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/applyLayoutFixes.js
  client/app/visualizations/chart/plotly/fixtures/prepareData/bar/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/bar/normalized.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/bar/stacked.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/box/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/box/with-points.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/bubble/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/heatmap/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/heatmap/reversed.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/heatmap/sorted-reversed.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/heatmap/sorted.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/heatmap/with-labels.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/keep-missing-values.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/missing-values-0.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/normalized-stacked.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/normalized.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/line-area/stacked.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/custom-tooltip.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/without-labels.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/without-x.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/scatter/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/scatter/without-labels.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/box-single-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/box-with-second-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-single-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-with-second-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-with-stacking.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-without-legend.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie-multiple-series.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie-without-annotations.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie.json
  client/app/visualizations/chart/plotly/index.js
  client/app/visualizations/chart/plotly/prepareData.js
  client/app/visualizations/chart/plotly/prepareData.test.js
  client/app/visualizations/chart/plotly/prepareDefaultData.js
  client/app/visualizations/chart/plotly/prepareHeatmapData.js
  client/app/visualizations/chart/plotly/prepareLayout.js
  client/app/visualizations/chart/plotly/prepareLayout.test.js
  client/app/visualizations/chart/plotly/preparePieData.js
  client/app/visualizations/chart/plotly/updateData.js
  client/app/visualizations/chart/plotly/utils.js
  client/app/visualizations/choropleth/utils.js
Labels: Frontend, Visualizations, Visualizations: Chart

#4134 Alerts: Add more condition comparison options
  redash/models/__init__.py
Labels: Backend, Feature: Alerts, enhancement

#4130 Migrate Chart visualization to React Part 1: Renderer
  client/app/assets/less/main.less
  client/app/pages/dashboards/dashboard.less
  client/app/visualizations/EditVisualizationDialog.jsx
  client/app/visualizations/chart/Renderer/CustomPlotlyChart.jsx
  client/app/visualizations/chart/Renderer/PlotlyChart.jsx
  client/app/visualizations/chart/Renderer/index.jsx
  client/app/visualizations/chart/Renderer/renderer.less
  client/app/visualizations/chart/chart-editor.html
  client/app/visualizations/chart/chart.html
  client/app/visualizations/chart/index.js
  client/app/visualizations/chart/plotly/customChartUtils.js
  client/app/visualizations/chart/plotly/index.js
Labels: Frontend, Frontend: React, Visualizations, Visualizations: Chart

#4138 Counter Editor: move components to own files
  client/app/visualizations/counter/Editor.jsx
  client/app/visualizations/counter/Editor/FormatSettings.jsx
  client/app/visualizations/counter/Editor/GeneralSettings.jsx
  client/app/visualizations/counter/Editor/index.jsx
Labels: Frontend

#4136 Color picker component
  client/app/components/ColorBox.jsx
  client/app/components/ColorPicker/Input.jsx
  client/app/components/ColorPicker/Swatch.jsx
  client/app/components/ColorPicker/index.jsx
  client/app/components/ColorPicker/index.less
  client/app/components/ColorPicker/input.less
  client/app/components/ColorPicker/swatch.less
  client/app/components/color-box.less
  package.json
Labels: Frontend

#4020 Migrate Widget component to React
  client/app/assets/less/inc/visualizations/misc.less
  client/app/assets/less/inc/visualizations/pivot-table.less
  client/app/assets/less/redash/query.less
  client/app/components/Parameters.jsx
  client/app/components/QueryLink.jsx
  client/app/components/Timer.jsx
  client/app/components/dashboards/AutoHeightController.js
  client/app/components/dashboards/DashboardGrid.jsx
  client/app/components/dashboards/ExpandedWidgetDialog.jsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/dashboards/dashboard-grid.less
  client/app/components/dashboards/dashboard-widget/RestrictedWidget.jsx
  client/app/components/dashboards/dashboard-widget/TextboxWidget.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/dashboards/dashboard-widget/Widget.jsx
  client/app/components/dashboards/dashboard-widget/Widget.less
  client/app/components/dashboards/dashboard-widget/index.js
  client/app/components/dashboards/widget-dialog.html
  client/app/components/dashboards/widget-dialog.less
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/components/query-link.js
  client/app/lib/hooks/useQueryResult.js
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/pages/dashboards/dashboard.less
  client/app/pages/dashboards/public-dashboard-page.html
  client/app/pages/dashboards/public-dashboard-page.js
  client/app/services/query.js
  client/app/services/widget.js
  client/app/visualizations/VisualizationName.jsx
  client/app/visualizations/VisualizationName.less
  client/app/visualizations/VisualizationRenderer.jsx
  client/cypress/integration/dashboard/textbox_spec.js
  client/cypress/integration/dashboard/widget_spec.js
Labels: Frontend, Frontend: React

#4133 Migrate Pivot Table visualization to React
  client/app/assets/less/inc/visualizations/pivot-table.less
  client/app/assets/less/redash/query.less
  client/app/components/Filters.jsx
  client/app/filters/index.js
  client/app/pages/dashboards/dashboard.less
  client/app/visualizations/pivot/Renderer.jsx
  client/app/visualizations/pivot/index.js
  client/app/visualizations/pivot/pivottable-editor.html
  client/app/visualizations/pivot/renderer.less
  client/cypress/integration/visualizations/pivot_spec.js
  client/cypress/support/commands.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, Visualizations

#4199 Sortable component
  client/app/components/Parameters.jsx
  client/app/components/Parameters.less
  client/app/components/sortable/index.jsx
  client/app/components/sortable/style.less
  package-lock.json
  package.json
Labels: Frontend
