Repository getredash/redash, pull requests merged in 2019-08, with the labels that each got.

#4035 Counter visualization: formatting not applied to target value
  client/app/visualizations/counter/counter.html
  client/app/visualizations/counter/index.js
  package-lock.json
  package.json
Labels: Frontend, Visualizations, Visualizations: Counter

#3952 Support multi-select in parameters
  client/app/components/EditParameterSettingsDialog.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/components/parameters.js
  client/app/services/query.js
  client/cypress/integration/query/parameter_spec.js
  redash/models/parameterized_query.py
  redash/tasks/queries.py
  tests/models/test_parameterized_query.py
Labels: Backend, Frontend

#4037 Visualisation editor crashes out when changing datetype to non-HTML text
  client/app/lib/value-format.js
Labels: Bug, Frontend

#4040 Allow dynamic values dropdown to scroll with the page
  client/app/components/dynamic-parameters/DynamicButton.jsx
Labels: Frontend

#4051 Make sure there is an event for any query execution
  redash/handlers/query_results.py
Labels: Backend

#4045 refresh_queries requires Request Context
  redash/handlers/queries.py
  redash/handlers/query_results.py
  redash/models/__init__.py
  redash/models/parameterized_query.py
  redash/tasks/queries.py
  tests/models/test_parameterized_query.py
  tests/tasks/test_refresh_queries.py
Labels: Backend, Bug

#4056 Align content vertically in restricted widget type
  client/app/components/dashboards/widget.html
Labels: Frontend

#3168 Add tag management commands
  redash/cli/__init__.py
  redash/cli/queries.py
Labels: enhancement

#2631 Dont send password reset link to disabled users
  redash/authentication/account.py
  redash/handlers/authentication.py
  redash/templates/emails/reset_disabled.html
  redash/templates/emails/reset_disabled.txt
  tests/test_authentication.py
Labels: Backend

#4063 Add option to control whether to format target value.
  client/app/visualizations/counter/counter-editor.html
  client/app/visualizations/counter/index.js
Labels: Frontend

#4062 Prevent CSP violations by not having script URLs
  client/.eslintrc.js
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/FavoritesControl.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/HelpTrigger.less
  client/app/components/QuerySelector.jsx
  client/app/components/TagsList.jsx
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/empty-state/empty-state.less
  client/app/pages/dashboards/dashboard.html
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
Labels: Bug, Frontend

#4032 Add parameter dialog doesn't work when query has selected text
  client/app/pages/queries/source-view.js
Labels: Bug, Feature: Parameters, Frontend

#4072 ParameterizedQuery: handle the case where a value is null
  redash/models/parameterized_query.py
  tests/models/test_parameterized_query.py
Labels: Backend

#4073 Format Counter target value as a number with reasonable default
  client/app/visualizations/counter/index.js
Labels: Frontend

#4006 Migrate Parameters component to React
  client/app/components/EditParameterSettingsDialog.jsx
  client/app/components/ParameterApplyButton.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/ParameterValueInput.less
  client/app/components/Parameters.jsx
  client/app/components/Parameters.less
  client/app/components/parameters.html
  client/app/components/parameters.js
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
  client/app/services/query.js
  client/cypress/integration/dashboard/grid_compliant_widgets_spec.js
  client/cypress/integration/query/parameter_spec.js
  client/cypress/support/commands.js
  client/cypress/support/dashboard/index.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4090 Fix: MySQL connections without SSL are failing
  redash/query_runner/mysql.py
Labels: Backend, Bug

#3804 Dashboard: when updating parameters, run only relevant queries
  client/app/components/Parameters.jsx
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/pages/dashboards/dashboard.js
Labels: Frontend
