Repository getredash/redash, pull requests merged in 2019-01, with the labels that each got.

#3231 Delete an unused global
  webpack.config.js
Labels: in progress

#3236 Fix: forked query wasn't opening in MULTI_ORG env
  client/app/pages/queries/view.js
Labels: in progress, review

#3235 Send argsrepr value with execute_query task
  redash/tasks/queries.py
Labels: in progress, review

#3237 request.view_args might be None and add org_id to ApiUser
  redash/authentication/__init__.py
  redash/authentication/org_resolving.py
  redash/models.py
Labels: in progress, review

#3238 Handle the case when a QueryTracker is None and change order.
  redash/tasks/queries.py
Labels: in progress, needs-more-info, review

#3239 Fix: Query editor duplicates keystrokes (#2972)
  client/app/components/QueryEditor.jsx
Labels: in progress, review, typescript-ftw

#3243 Scatter charts can have category Y axis similar to Bubble
  client/app/visualizations/chart/plotly/utils.js
Labels: Bug, Frontend, Visualizations: Chart, in progress, review

#3245 Upgrade Requests package
  requirements.txt
Labels: review

#2426 Closes #2396: Add finer-grained scheduling.
  client/app/assets/less/redash/ant.less
  client/app/components/queries/ScheduleDialog.css
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/schedule-dialog.html
  client/app/components/queries/schedule-dialog.js
  client/app/filters/index.js
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
  client/app/services/query.js
  migrations/versions/640888ce445d_.py
  redash/models.py
  tests/factories.py
  tests/handlers/test_queries.py
  tests/tasks/test_queries.py
  tests/test_models.py
Labels: Backend, Frontend, Frontend: React, in progress, review

#3242 Feature: Refresh schedule - code optimizations
  client/app/components/queries/ScheduleDialog.jsx
  client/app/filters/index.js
Labels: in progress, review

#3246 Feature: Refresh schedule - save/cancel actions
  client/app/assets/less/redash/ant.less
  client/app/components/queries/ScheduleDialog.jsx
Labels: in progress, review

#3247 Feature: Refresh schedule - styling
  client/app/assets/less/redash/ant.less
  client/app/components/queries/ScheduleDialog.css
  client/app/components/queries/ScheduleDialog.jsx
Labels: in progress, review

#3250 Fix: Refresh schedule phrase overlaps title
  client/app/components/queries/ScheduleDialog.css
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/SchedulePhrase.jsx
  client/app/filters/index.js
  client/app/pages/admin/outdated-queries/outdated-queries.html
  client/app/pages/queries-list/queries-list.html
  client/app/pages/queries/query.html
Labels: in progress, review

#3026 Add "Active at" column to user list.
  Makefile
  client/app/pages/users/list.html
  migrations/versions/e7f8a917aa8e_add_user_details_json_column.py
  redash/__init__.py
  redash/authentication/__init__.py
  redash/handlers/organization.py
  redash/handlers/users.py
  redash/models/__init__.py
  redash/models/base.py
  redash/models/changes.py
  redash/models/mixins.py
  redash/models/organizations.py
  redash/models/types.py
  redash/models/users.py
  redash/monitor.py
  redash/tasks/__init__.py
  redash/tasks/general.py
  redash/tasks/queries.py
  redash/utils/__init__.py
  redash/worker.py
  requirements.txt
  setup.cfg
  tests/handlers/test_users.py
  tests/handlers/test_visualizations.py
  tests/models/test_query_results.py
  tests/tasks/test_queries.py
  tests/test_models.py
Labels: review

#3256 Redis based implementation of user active_at timestamp update
  redash/__init__.py
  redash/models/__init__.py
  redash/models/base.py
  redash/models/types.py
  redash/models/users.py
  redash/tasks/general.py
  requirements.txt
  tests/models/test_users.py
  tests/test_models.py
Labels: in progress, review

#3262 update Flask-OAuthLib
  requirements.txt
Labels: in progress, review

#3188 [Data Sources] Implement Apache Drill
  client/app/assets/images/db-logos/drill.png
  redash/query_runner/__init__.py
  redash/query_runner/drill.py
  redash/query_runner/google_spreadsheets.py
  redash/query_runner/query_results.py
  redash/settings/__init__.py
  tests/query_runner/test_drill.py
  tests/query_runner/test_google_spreadsheets.py
  tests/query_runner/test_http.py
  tests/query_runner/test_query_results.py
  tests/query_runner/test_utils.py
Labels: Backend, in progress

#3265 Fix: Refresh schedule interval count doesn't adhere to permission rules
  client/app/components/queries/ScheduleDialog.jsx
  client/app/filters/index.js
Labels: review

#3274 Allows omitting single value number in durationHumanize
  client/app/components/queries/SchedulePhrase.jsx
  client/app/filters/index.js
Labels: in progress, review

#3268 Fix: Refresh schedule durations not pluralized sufficiently
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/SchedulePhrase.jsx
  client/app/filters/index.js
Labels: review

#3267 Verify admin email address
  client/app/components/empty-state/empty-state.html
  client/app/pages/home/home.html
  client/app/pages/home/index.js
  client/app/pages/users/new.html
  client/app/pages/users/new.js
  client/app/pages/users/show.js
  redash/authentication/account.py
  redash/handlers/authentication.py
  redash/handlers/setup.py
  redash/handlers/users.py
  redash/models/users.py
  redash/templates/emails/verify.html
  redash/templates/emails/verify.txt
  redash/templates/layouts/signed_out.html
  redash/templates/verify.html
Labels: review

#3273 handlers: Fix post users
  redash/handlers/users.py
  tests/handlers/test_users.py
Labels: in progress, review

#3282 Pin pyparsing version
  requirements.txt
Labels: in progress, review

#3279 Separate Bootstrap/Ant styling
  client/app/assets/less/ant.less
  client/app/assets/less/inc/variables.less
  client/app/assets/less/main.less
  client/app/assets/less/redash/redash-newstyle.less
  webpack.config.js
Labels: in progress, review

#2756 Dashboard Parameters
  client/.eslintrc.js
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/DateInput.jsx
  client/app/components/DateRangeInput.jsx
  client/app/components/DateTimeInput.jsx
  client/app/components/DateTimeRangeInput.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/components/dashboards/AddTextboxDialog.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dashboards/add-widget-dialog.html
  client/app/components/dashboards/add-widget-dialog.js
  client/app/components/dashboards/add-widget-dialog.less
  client/app/components/dashboards/widget.html
  client/app/components/dashboards/widget.js
  client/app/components/parameter-input.html
  client/app/components/parameter-settings.html
  client/app/components/parameters.html
  client/app/components/parameters.js
  client/app/components/query-based-parameter.html
  client/app/components/tags-control/TagsEditorModal.jsx
  client/app/lib/highlight.js
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/app/services/dashboard.js
  client/app/services/query.js
  client/app/services/widget.js
Labels: Feature: Parameters, Frontend, Frontend: React, UX, enhancement, in progress, review

#3209 Migrate DynamicForm to React
  client/app/assets/less/ant.less
  client/app/components/dynamic-form.html
  client/app/components/dynamic-form.js
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/dynamic-form/dynamicFormHelper.js
  client/app/components/proptypes.js
  client/app/pages/data-sources/show.js
  client/app/pages/destinations/show.html
  client/app/pages/destinations/show.js
  client/app/services/toastr.js
  cypress/integration/data-source/create_data_source_spec.js
Labels: Frontend, Frontend: React, in progress, review

#3298 Fix invitation pending for older invitations
  redash/handlers/authentication.py
  tests/handlers/test_authentication.py
Labels: in progress, review

#3283 Handling empty query.schedule
  client/app/components/proptypes.js
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/SchedulePhrase.jsx
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  client/app/pages/queries/query.html
Labels: review, typescript-ftw

#3299 Multifilter's dropdown cropped when visualization container is too small
  client/app/components/filters.html
Labels: Bug, Frontend, in progress, review

#3277 Use None as "not scheduled" default value of a query
  client/app/components/proptypes.js
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/ScheduleDialog.test.js
  client/app/components/queries/SchedulePhrase.jsx
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  client/app/pages/queries/query.html
  client/app/services/query.js
  migrations/versions/73beceabb948_bring_back_null_schedule.py
  redash/models/__init__.py
  redash/models/types.py
  tests/factories.py
  tests/models/test_dashboards.py
  tests/test_models.py
Labels: in progress, review

#3296 Update form text colors
  client/app/assets/less/ant.less
  client/app/assets/less/inc/ant-variables.less
  client/app/assets/less/inc/variables.less
  cypress/integration/data-source/create_data_source_spec.js
Labels: in progress, review

#3288 Allow execution of highlighted subquery
  client/app/components/QueryEditor.css
  client/app/components/QueryEditor.jsx
  client/app/pages/queries/query.html
  client/app/pages/queries/view.js
  client/app/services/query.js
Labels: in progress

#3307 Override default number formats with environment variables
  redash/handlers/authentication.py
  redash/settings/organization.py
Labels: in progress

#3224 Add regenerate function of user's API key
  client/app/pages/users/show.html
  client/app/pages/users/show.js
  redash/handlers/api.py
  redash/handlers/users.py
  redash/models/users.py
  tests/handlers/test_users.py
  tests/models/test_users.py
Labels: review

#3320 Fix Percy data source page always showing diff
  cypress/integration/data-source/create_data_source_spec.js
Labels: in progress, review

#3304 support for fetching all JQL results by way of pagination (fixes #1720)
  redash/query_runner/jql.py
Labels: in progress

#3317 Use Ant's Paginator component; migrate SortIcon to React
  client/app/assets/less/ant.less
  client/app/assets/less/inc/ant-variables.less
  client/app/assets/less/inc/visualizations/misc.less
  client/app/assets/less/redash/query.less
  client/app/components/Paginator.jsx
  client/app/components/SortIcon.jsx
  client/app/components/dynamic-table/dynamic-table.html
  client/app/components/dynamic-table/index.js
  client/app/components/paginator.js
  client/app/components/sort-icon.js
  client/app/lib/pagination/live-paginator.js
Labels: Frontend: React, in progress, review

#3311 Textless query result endpoint
  redash/handlers/api.py
  redash/handlers/query_results.py
  tests/handlers/test_query_results.py
Labels: review

#3327 Add configuration for the Support probot.
  .github/support.yml
Labels: in progress

#3329 Remove link to roadmap
  CONTRIBUTING.md
Labels: PR: unreviewed, in progress

#3319 Add: Uptycs query runner
  client/app/assets/images/db-logos/uptycs.png
  redash/query_runner/uptycs.py
  redash/settings/__init__.py
Labels: PR: unreviewed, in progress

#3324 Migrate PageHeader component to React
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/PageHeader.jsx
  client/app/components/page-header/index.js
  client/app/components/page-header/page-header.html
  client/app/components/settings-screen.html
  client/app/pages/admin/outdated-queries/outdated-queries.html
  client/app/pages/admin/status/status.html
  client/app/pages/admin/tasks/tasks.html
  client/app/pages/alert/alert.html
  client/app/pages/alerts-list/alerts-list.html
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/dashboards/public-dashboard-page.html
  client/app/pages/queries-list/queries-list.html
Labels: Frontend: React, PR: unreviewed, in progress

#3331 Convert Angular services to CommonJS-style and use them in React components instead of injecting
  client/app/components/AutocompleteToggle.jsx
  client/app/components/DateInput.jsx
  client/app/components/DateRangeInput.jsx
  client/app/components/DateTimeInput.jsx
  client/app/components/DateTimeRangeInput.jsx
  client/app/components/Footer.jsx
  client/app/components/Footer.test.js
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/components/QueryEditor.jsx
  client/app/components/dashboards/AddTextboxDialog.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/EditParameterMappingsDialog.jsx
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/tags-control/DashboardTagsControl.jsx
  client/app/components/tags-control/QueryTagsControl.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/index.js
  client/app/pages/queries/view.js
  client/app/services/alert-dialog.js
  client/app/services/alert-subscription.js
  client/app/services/alert.js
  client/app/services/auth.js
  client/app/services/dashboard.js
  client/app/services/data-source.js
  client/app/services/destination.js
  client/app/services/events.js
  client/app/services/getTags.js
  client/app/services/group.js
  client/app/services/http.js
  client/app/services/keyboard-shortcuts.js
  client/app/services/ng.js
  client/app/services/notifications.js
  client/app/services/offline-listener.js
  client/app/services/organization-status.js
  client/app/services/query-snippet.js
  client/app/services/query.js
  client/app/services/recordEvent.js
  client/app/services/toastr.js
  client/app/services/user.js
  client/app/services/widget.js
Labels: Frontend: React, PR: unreviewed, PR: waiting-for-feedback, in progress

#3356 Move BigQueryGCE to its own file
  redash/query_runner/big_query.py
  redash/query_runner/big_query_gce.py
Labels: PR: unreviewed, in progress

#3338 Add Percy Page Screenshots
  cypress/integration/data-source/create_data_source_spec.js
  cypress/integration/percy/page_screenshots.js
  cypress/integration/query/create_query_spec.js
  cypress/integration/user/login_spec.js
Labels: PR: unreviewed, in progress

#2934 Show dashboard creator on dashboard page
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.less
Labels: in progress

#3357 Widget params: Date/Date range value empty in static param input
  client/app/components/ParameterMappingInput.jsx
Labels: Bug, Frontend, PR: reviewed-approved, PR: unreviewed, in progress

#3345 Refactor Policy and OrganizationStatus services
  client/app/components/dashboards/edit-dashboard-dialog.js
  client/app/components/empty-state/empty-state.js
  client/app/config/index.js
  client/app/pages/dashboards/dashboard.js
  client/app/pages/data-sources/list.js
  client/app/pages/queries/view.js
  client/app/pages/users/list.js
  client/app/services/ng.js
  client/app/services/organization-status.js
  client/app/services/organizationStatus.js
  client/app/services/policy.js
  client/app/services/policy/DefaultPolicy.js
  client/app/services/policy/index.js
Labels: Frontend, PR: unreviewed, in progress

#3358 Cypress tests: preset the admin API key to a static value
  .circleci/config.yml
  cypress/cypress.js
Labels: PR: reviewed-approved, in progress

#3315 Server-side parameter validation
  redash/handlers/query_results.py
  redash/utils/parameterized_query.py
  tests/utils/test_parameterized_query.py
Labels: PR: unreviewed, PR: waiting-for-feedback, review

#3253 frontend lint update
  .codeclimate.yml
  client/.eslintrc.js
  client/app/components/EditInPlace.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/QueryEditor.jsx
  client/app/components/app-view/index.js
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/tags-list/tags-list.js
  client/app/filters/datetime.js
  client/app/filters/markdown.js
  client/app/pages/data-sources/show.js
  client/app/pages/queries/view.js
  client/app/pages/settings/organization.js
  client/app/services/query-result.js
  client/app/services/query.js
  client/app/visualizations/chart/index.js
  client/app/visualizations/sankey/index.js
  package-lock.json
  package.json
Labels: PR: reviewed-approved, in progress

#3360 Yandex Metrica: changed Auth from params to headers
  redash/query_runner/yandex_metrica.py
Labels: PR: unreviewed, in progress

#3359 Filename set when /results called directly
  redash/handlers/query_results.py
Labels: PR: unreviewed, in progress

#3363 Fix: Escape button in tag edit modal
  client/app/components/tags-control/TagsControl.jsx
  client/app/components/tags-control/TagsEditorModal.jsx
Labels: PR: reviewed-approved, in progress

#3286 Update CodeClimate configuration format to Version 2
  .codeclimate.yml
Labels: PR: unreviewed, in progress

#3362 Fix: make ClickHouse password and username truly optional
  redash/query_runner/clickhouse.py
Labels: PR: reviewed-approved, in progress

#3369 Fix: Static param value not editable for Text/Number
  client/app/components/ParameterValueInput.jsx
Labels: PR: reviewed-approved, in progress

#3368 React migration: FavoritesControl and TagsList components
  client/app/components/FavoritesControl.jsx
  client/app/components/TagsList.jsx
  client/app/components/favorites-control/index.js
  client/app/components/tags-list/tags-list.html
  client/app/components/tags-list/tags-list.js
  client/app/lib/list-ctrl.js
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/queries-list/queries-list.html
  client/app/services/ng.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React, PR: unreviewed, in progress

#3370 Tune CodeClimate's config to make it less annoying
  .codeclimate.yml
Labels: PR: unreviewed, in progress

#3348 Fix some incompatible dependencies
  requirements.txt
  requirements_all_ds.txt
  requirements_dev.txt
Labels: PR: waiting-for-feedback, in progress

#3373 Migrate EmptyState component to React
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/empty-state/empty-state.html
  client/app/components/empty-state/empty-state.js
  client/app/pages/alerts-list/alerts-list.html
  client/app/pages/dashboards/dashboard-list.html
  client/app/pages/home/home.html
  client/app/pages/queries-list/queries-list.html
Labels: Frontend, Frontend: React, PR: reviewed-approved, PR: unreviewed, in progress

#3380 [Widget Params] Url prefix change p -> p_w
  client/app/services/widget.js
Labels: PR: reviewed-approved, in progress

#3347 Show unpublished queries as disabled in the alert and dashboard modals.
  client/app/assets/less/redash/redash-newstyle.less
  client/app/assets/less/redash/tags-control.less
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/pages/alert/alert.html
Labels: PR: reviewed-approved, in progress

#3382 BigQuery should correctly handle tables that do not have a schema key
  redash/query_runner/big_query.py
Labels: PR: unreviewed, in progress
