Repository getredash/redash, pull requests merged in 2019-10, with the labels that each got.

#4147 Add interface to abstract query result persistence
  redash/models/__init__.py
  redash/models/parameterized_query.py
  redash/query_runner/python.py
  redash/serializers/query_result.py
  redash/settings/dynamic_settings.py
  redash/tasks/queries.py
  tests/models/test_queries.py
  tests/models/test_query_results.py
  tests/tasks/test_queries.py
  tests/test_models.py
Labels: Backend

#4224 Postgres: make sure table from the public schema doesn't get merged with table from other schemas
  redash/query_runner/pg.py
  tests/query_runner/test_pg.py
Labels: Backend

#4232 (Python 3) Use Redis' decode_responses=True option
  redash/__init__.py
  redash/models/__init__.py
  redash/models/users.py
  redash/settings/__init__.py
  redash/settings/helpers.py
  tests/test_models.py
Labels: Backend, Python 3

#4240 Implemented new condition comparison options
  client/app/components/proptypes.js
  client/app/pages/alert/Alert.jsx
  client/app/pages/alert/components/Criteria.jsx
  client/app/services/alert.js
  client/cypress/integration/alert/edit_alert_spec.js
Labels: Feature: Alerts, Frontend

#4255 Migrate Sankey renderer to React
  client/app/pages/queries/query.html
  client/app/visualizations/sankey/Renderer.jsx
  client/app/visualizations/sankey/d3sankey.js
  client/app/visualizations/sankey/index.js
  client/app/visualizations/sankey/initSankey.js
  client/cypress/integration/visualizations/sankey_sunburst_spec.js
Labels: Frontend, Frontend: React, Visualizations

#4252 Restore <body> bottom padding
  client/app/assets/less/inc/base.less
  client/app/assets/less/redash/query.less
  client/app/pages/dashboards/dashboard.less
Labels: Bug, Frontend

#4268 Add "use-debounce" dependency
  package-lock.json
  package.json
Labels: Frontend

#4280 Fix get_next_path tests
  redash/authentication/__init__.py
  requirements.txt
  tests/__init__.py
  tests/test_authentication.py
Labels: Backend, Python 3

#4175 Migrate Table visualization to React Part 2: Editor
  client/app/visualizations/table/Editor/ColumnEditor.jsx
  client/app/visualizations/table/Editor/ColumnsSettings.jsx
  client/app/visualizations/table/Editor/ColumnsSettings.test.js
  client/app/visualizations/table/Editor/GridSettings.jsx
  client/app/visualizations/table/Editor/GridSettings.test.js
  client/app/visualizations/table/Editor/__snapshots__/ColumnsSettings.test.js.snap
  client/app/visualizations/table/Editor/__snapshots__/GridSettings.test.js.snap
  client/app/visualizations/table/Editor/editor.less
  client/app/visualizations/table/Editor/index.jsx
  client/app/visualizations/table/columns/__snapshots__/boolean.test.js.snap
  client/app/visualizations/table/columns/__snapshots__/datetime.test.js.snap
  client/app/visualizations/table/columns/__snapshots__/image.test.js.snap
  client/app/visualizations/table/columns/__snapshots__/link.test.js.snap
  client/app/visualizations/table/columns/__snapshots__/number.test.js.snap
  client/app/visualizations/table/columns/__snapshots__/text.test.js.snap
  client/app/visualizations/table/columns/boolean.js
  client/app/visualizations/table/columns/boolean.jsx
  client/app/visualizations/table/columns/boolean.test.js
  client/app/visualizations/table/columns/datetime.js
  client/app/visualizations/table/columns/datetime.jsx
  client/app/visualizations/table/columns/datetime.test.js
  client/app/visualizations/table/columns/image.js
  client/app/visualizations/table/columns/image.jsx
  client/app/visualizations/table/columns/image.test.js
  client/app/visualizations/table/columns/index.js
  client/app/visualizations/table/columns/json.jsx
  client/app/visualizations/table/columns/link.js
  client/app/visualizations/table/columns/link.jsx
  client/app/visualizations/table/columns/link.test.js
  client/app/visualizations/table/columns/number.js
  client/app/visualizations/table/columns/number.jsx
  client/app/visualizations/table/columns/number.test.js
  client/app/visualizations/table/columns/text.js
  client/app/visualizations/table/columns/text.jsx
  client/app/visualizations/table/columns/text.test.js
  client/app/visualizations/table/getOptions.js
  client/app/visualizations/table/index.js
  client/app/visualizations/table/table-editor.html
  client/app/visualizations/table/table-editor.less
  client/app/visualizations/table/utils.js
Labels: Frontend: React, Visualizations, Visualizations: Table

#4300 Show more workers per page
  client/app/components/admin/RQStatus.jsx
Labels: Frontend
