Repository getredash/redash, pull requests merged in 2019-07, with the labels that each got.

#3930 Migrate Word Cloud visualization to React
  client/app/directives/resize-event.js
  client/app/lib/hooks/useQueryResult.js
  client/app/pages/dashboards/dashboard.less
  client/app/services/resizeObserver.js
  client/app/visualizations/EditVisualizationDialog.jsx
  client/app/visualizations/word-cloud/Editor.jsx
  client/app/visualizations/word-cloud/Renderer.jsx
  client/app/visualizations/word-cloud/index.js
  client/app/visualizations/word-cloud/renderer.less
  client/cypress/integration/visualizations/edit_visualization_dialog_spec.js
  client/cypress/integration/visualizations/word_cloud_spec.js
  client/cypress/support/commands.js
  webpack.config.js
Labels: Frontend, Visualizations

#3951 Fix: Details Visualization: render date/time values as strings and not epoch time
  client/app/visualizations/details/DetailsRenderer.jsx
Labels: Bug, Frontend, Visualizations

#3948 Migrate Box Plot visualization to React
  client/app/pages/dashboards/dashboard.less
  client/app/services/resizeObserver.js
  client/app/visualizations/box-plot/Editor.jsx
  client/app/visualizations/box-plot/Renderer.jsx
  client/app/visualizations/box-plot/d3box.js
  client/app/visualizations/box-plot/index.js
  client/app/visualizations/box-plot/renderer.less
  client/app/visualizations/word-cloud/Renderer.jsx
  client/cypress/integration/visualizations/box_plot_spec.js
  client/cypress/integration/visualizations/word_cloud_spec.js
  cypress.json
Labels: Frontend, Visualizations

#3627 Migrate Query Snippets to React
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/items-list/components/ItemsTable.jsx
  client/app/components/proptypes.js
  client/app/components/query-snippets/QuerySnippetDialog.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/query-snippets/QuerySnippetsList.less
  client/app/pages/query-snippets/edit.html
  client/app/pages/query-snippets/edit.js
  client/app/pages/query-snippets/list.html
  client/app/pages/query-snippets/list.js
  client/app/services/navigateTo.js
  client/app/services/policy/DefaultPolicy.js
Labels: Frontend: React

#3968 Archiving a dashboard cause widgets to show reload spinner forever
  client/app/pages/dashboards/dashboard.js
Labels: Feature: Dashboards, Frontend, UX

#3137 Build custom alert message
  client/app/pages/alert/alert.html
  client/app/pages/alert/index.js
  client/app/services/alert-template.js
  redash/destinations/chatwork.py
  redash/destinations/email.py
  redash/destinations/hangoutschat.py
  redash/destinations/mattermost.py
  redash/destinations/pagerduty.py
  redash/destinations/slack.py
  redash/destinations/webhook.py
  redash/handlers/alerts.py
  redash/handlers/authentication.py
  redash/models/__init__.py
  redash/settings/__init__.py
  redash/tasks/alerts.py
Labels: in progress

#3805 JSON Data Source
  client/app/assets/images/db-logos/json.png
  redash/query_runner/json_ds.py
  redash/settings/__init__.py
Labels: Backend

#3976 Plotly legent overlaps plot on small screens (when legend clicked)
  client/app/visualizations/chart/plotly/utils.js
Labels: Bug, Frontend, Visualizations: Chart

#3898 Celery doesn't auto reload in development
  bin/docker-entrypoint
  docker-compose.yml
  requirements_dev.txt
Labels: Backend, Bug

#3985 Query Result API response shouldn't include query information for non authenticated users
  redash/handlers/query_results.py
  redash/serializers/__init__.py
  redash/serializers/query_result.py
  tests/serializers/test_query_results.py
Labels: Backend

#3972 Add "deprecated" flag to query runners (and alert destinations)
  redash/destinations/__init__.py
  redash/destinations/hipchat.py
  redash/handlers/data_sources.py
  redash/handlers/destinations.py
  redash/query_runner/__init__.py
  redash/query_runner/url.py
  redash/utils/__init__.py
  tests/handlers/test_data_sources.py
  tests/handlers/test_destinations.py
Labels: Backend

#3904 Add Dynamic Values to Date and Date Range Parameters
  client/app/assets/less/ant.less
  client/app/components/DateInput.jsx
  client/app/components/DateRangeInput.jsx
  client/app/components/DateTimeInput.jsx
  client/app/components/DateTimeRangeInput.jsx
  client/app/components/EditParameterSettingsDialog.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/dynamic-parameters/DateParameter.jsx
  client/app/components/dynamic-parameters/DateRangeParameter.jsx
  client/app/components/dynamic-parameters/DynamicButton.jsx
  client/app/components/dynamic-parameters/DynamicButton.less
  client/app/components/dynamic-parameters/DynamicParameters.less
  client/app/components/parameters.js
  client/app/components/proptypes.js
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
  client/app/services/dashboard.js
  client/app/services/query.js
  client/cypress/integration/query/parameter_spec.js
  package-lock.json
  package.json
Labels: Frontend

#3970 Added widget header refresh indicator
  client/app/assets/less/redash/redash-newstyle.less
  client/app/components/Timer.jsx
  client/app/components/dashboards/widget.html
  client/app/pages/dashboards/dashboard.html
  client/app/pages/dashboards/dashboard.js
  client/cypress/integration/dashboard/widget_spec.js
Labels: Frontend

#4012 Updated timeago strings
  client/app/components/TimeAgo.jsx
  client/app/config/index.js
Labels: Frontend

#3963 Migrate Table visualization to React Part 1: Renderer
  client/app/assets/less/inc/ant-variables.less
  client/app/components/HtmlContent.jsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/dynamic-table/default-cell/index.js
  client/app/components/dynamic-table/default-cell/template.html
  client/app/components/dynamic-table/default-cell/utils.js
  client/app/components/dynamic-table/dynamic-table-row.js
  client/app/components/dynamic-table/dynamic-table.html
  client/app/components/dynamic-table/dynamic-table.less
  client/app/components/dynamic-table/index.js
  client/app/components/dynamic-table/json-cell/index.js
  client/app/components/dynamic-table/json-cell/json-view-interactive.js
  client/app/components/dynamic-table/json-cell/template.html
  client/app/components/json-view-interactive/JsonViewInteractive.jsx
  client/app/components/json-view-interactive/json-view-interactive.less
  client/app/lib/value-format.js
  client/app/pages/queries/query.html
  client/app/visualizations/VisualizationRenderer.jsx
  client/app/visualizations/index.js
  client/app/visualizations/table/Renderer.jsx
  client/app/visualizations/table/columns/boolean.js
  client/app/visualizations/table/columns/datetime.js
  client/app/visualizations/table/columns/image.js
  client/app/visualizations/table/columns/json.js
  client/app/visualizations/table/columns/link.js
  client/app/visualizations/table/columns/number.js
  client/app/visualizations/table/columns/text.js
  client/app/visualizations/table/index.js
  client/app/visualizations/table/renderer.less
  client/app/visualizations/table/table.html
  client/app/visualizations/table/utils.js
  client/cypress/integration/dashboard/sharing_spec.js
  client/cypress/integration/query/create_query_spec.js
  client/cypress/integration/query/parameter_spec.js
  client/cypress/integration/visualizations/table/.mocks/all-cell-types.js
  client/cypress/integration/visualizations/table/.mocks/large-dataset.js
  client/cypress/integration/visualizations/table/.mocks/multi-column-sort.js
  client/cypress/integration/visualizations/table/.mocks/search-in-data.js
  client/cypress/integration/visualizations/table/table_spec.js
  client/cypress/support/redash-api/index.js
Labels: Frontend, Frontend: React, Visualizations, Visualizations: Table

#4024 Dashboard-level filters not available when there are a textbox
  client/app/services/dashboard.js
Labels: Bug, Feature: Dashboards, Frontend

#4026 Cannot edit dashboard after adding widget
  redash/handlers/widgets.py
Labels: Bug, Feature: Dashboards, Frontend
