Repository getredash/redash, pull requests merged in 2019-12, with the labels that each got.

#4285 refreshing snowflake schema w/o waking cluster
  redash/query_runner/snowflake.py
Labels: Backend

#4412 Chart series switch places when picking Y axis or color
  client/app/visualizations/chart/getChartData.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#4408 Migrate AddToDashboard dialog
  client/app/components/app-header/AppHeader.jsx
  client/app/components/queries/AddToDashboardDialog.jsx
  client/app/components/queries/add-to-dashboard-dialog.less
  client/app/lib/hooks/useSearchResults.js
  client/app/pages/queries/add-to-dashboard.html
  client/app/pages/queries/add-to-dashboard.js
  client/app/pages/queries/view.js
Labels: Frontend, Frontend: React

#4385 Fix counter vizualization
  client/app/visualizations/counter/utils.js
  client/app/visualizations/counter/utils.test.js
Labels: Frontend, Visualizations, Visualizations: Counter

#4423 Change eslint configuration and fix resulting issues
  client/.eslintignore
  client/.eslintrc.js
  client/app/components/EditParameterSettingsDialog.jsx
  client/app/components/QuerySelector.jsx
  client/app/components/TimeAgo.jsx
  client/app/components/Timer.jsx
  client/app/components/app-header/components/FavoritesDropdown.jsx
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/permissions-editor/PermissionsEditorDialog.jsx
  client/app/components/users/ChangePasswordDialog.jsx
  client/app/components/users/UserEdit.jsx
  client/app/lib/hooks/useQueryResult.js
  client/app/lib/hooks/useSearchResults.js
  client/app/pages/alert/components/AlertDestinations.jsx
  client/app/pages/alert/components/MenuButton.jsx
  client/app/pages/alert/components/Rearm.jsx
  client/app/pages/home/Home.jsx
  client/app/services/query-string.js
  client/app/visualizations/EditVisualizationDialog.jsx
  client/app/visualizations/VisualizationRenderer.jsx
  client/app/visualizations/chart/Editor/SeriesSettings.jsx
  client/app/visualizations/chart/Renderer/CustomPlotlyChart.jsx
  client/app/visualizations/chart/Renderer/index.jsx
  client/app/visualizations/chart/plotly/prepareHeatmapData.js
  client/app/visualizations/choropleth/Editor/BoundsSettings.jsx
  client/app/visualizations/choropleth/Renderer/index.jsx
  client/app/visualizations/cohort/Cornelius.jsx
  client/app/visualizations/funnel/Renderer/index.jsx
  client/prettier.config.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4441 Adding application to Azure Kusto query runner
  redash/query_runner/azure_kusto.py
Labels: Backend

#4443 Map: add tooltip and popup templating
  client/app/assets/less/inc/visualizations/map.less
  client/app/visualizations/map/Editor/FormatSettings.jsx
  client/app/visualizations/map/Editor/index.js
  client/app/visualizations/map/getOptions.js
  client/app/visualizations/map/initMap.js
Labels: Frontend, Visualizations, Visualizations: Map

#4449 Third column not selectable for Bubble and Heatmap charts
  client/app/visualizations/chart/Editor/GeneralSettings.jsx
  client/app/visualizations/chart/Editor/GeneralSettings.test.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#4432 Migrate schema browser to react
  client/app/assets/less/inc/schema-browser.less
  client/app/assets/less/redash/query.less
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/SchemaBrowser.jsx
  client/app/pages/queries/query-source.less
  client/app/pages/queries/query.html
  client/app/services/query.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4452 Migrate Query page to React: Save changes
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/utils/archiveQuery.jsx
  client/app/pages/queries/utils/duplicateQuery.js
  client/app/pages/queries/utils/index.js
  client/app/pages/queries/utils/saveQuery.jsx
Labels: Frontend, Frontend: React

#4457 Migrate query source to React: Set of updates
  client/app/components/PermissionsEditorDialog/index.jsx
  client/app/components/PermissionsEditorDialog/index.less
  client/app/components/app-view/index.js
  client/app/components/queries/ApiKeyDialog/index.jsx
  client/app/components/queries/ApiKeyDialog/index.less
  client/app/directives/index.js
  client/app/directives/title.js
  client/app/pages/dashboards/dashboard.js
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/utils/index.js
  client/app/pages/queries/utils/updateQuery.jsx
  client/app/pages/queries/view.js
Labels: Frontend, Frontend: React

#4453 Migrate Query page to React: Visualization Tabs
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/utils/useVisualizationTabHandler.js
Labels: Frontend, Frontend: React

#4463 Migrate Query Source page to React: Visualizations area
  client/app/lib/hooks/useQueryResult.js
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/utils/updateQuery.jsx
  client/app/visualizations/EditVisualizationDialog.jsx
Labels: Frontend, Frontend: React

#4464 Refactor QueryEditor component
  client/app/assets/less/inc/ace-editor.less
  client/app/assets/less/inc/base.less
  client/app/assets/less/redash/query.less
  client/app/components/QueryEditor.css
  client/app/components/QueryEditor.jsx
  client/app/components/keywordBuilder.js
  client/app/components/queries/QueryEditor/AutocompleteToggle.jsx
  client/app/components/queries/QueryEditor/QueryEditorComponent.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.less
  client/app/components/queries/QueryEditor/ace.js
  client/app/components/queries/QueryEditor/index.jsx
  client/app/components/queries/QueryEditor/index.less
  client/app/pages/queries/query.html
  client/app/pages/queries/source-view.js
  client/app/pages/queries/view.js
Labels: Frontend

#4470 Migrate Query pages to React: Execute query hook
  client/app/pages/queries/utils/useQueryExecute.js
Labels: Frontend, Frontend: React

#4468 Migrate Query Source page to React: Editor area
  client/app/components/queries/QueryEditor/AngularWrapper.jsx
  client/app/components/queries/QueryEditor/QueryEditorComponent.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.less
  client/app/components/queries/QueryEditor/index.jsx
  client/app/components/queries/QueryEditor/index.less
  client/app/lib/hooks/useQueryResult.js
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryExecutionStatus.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/components/SchemaBrowser.jsx
  client/app/pages/queries/query-source.less
  client/app/pages/queries/utils/archiveQuery.jsx
  client/app/pages/queries/utils/editQueryVisualization.js
  client/app/pages/queries/utils/updateQuery.jsx
  client/app/pages/queries/utils/useQueryExecute.js
  client/app/pages/queries/utils/useVisualizationTabHandler.js
  client/app/services/keyboard-shortcuts.js
  client/app/services/query.js
Labels: Frontend, Frontend: React

#4486 Fix: query results query runner fails to load cached results.
  redash/query_runner/query_results.py
  tests/query_runner/test_query_results.py
Labels: Backend

#4476 Migrate Query Source page to React: metadata, schedule and description blocks
  client/app/assets/less/redash/query.less
  client/app/components/queries/SchedulePhrase.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryMetadata.jsx
  client/app/pages/queries/components/QueryMetadata.less
  client/app/pages/queries/utils/index.js
Labels: Frontend, Frontend: React

#4445 Support download as TSV File
  client/app/components/EditVisualizationButton/QueryControlDropdown.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/queries/VisualizationEmbed.jsx
  redash/handlers/query_results.py
  redash/serializers/__init__.py
  redash/serializers/query_result.py
  tests/serializers/test_query_results.py
Labels: Backend, Frontend

#3928 Chart: Bubble size control by coefficient and sizemode
  client/app/visualizations/chart/Editor/ColumnMappingSelect.jsx
  client/app/visualizations/chart/Editor/GeneralSettings.jsx
  client/app/visualizations/chart/getOptions.js
  client/app/visualizations/chart/plotly/fixtures/prepareData/bubble/default.json
  client/app/visualizations/chart/plotly/prepareDefaultData.js
Labels: Frontend, Visualizations

#4493 Update EditInPlace to use Antd components
  client/app/components/EditInPlace.jsx
  client/app/components/groups/GroupName.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/queries/query.html
Labels: Frontend

#4496 Migrate Query page to React: Cancel query execution
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryExecutionStatus.jsx
  client/app/pages/queries/utils/useQueryExecute.js
Labels: Frontend, Frontend: React

#4499 Migrate Query Source page to React: refine code
  client/app/components/queries/ApiKeyDialog/index.jsx
  client/app/components/queries/QueryEditor/index.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.less
  client/app/pages/queries/hooks/useAddNewParameterDialog.js
  client/app/pages/queries/hooks/useAddToDashboardDialog.js
  client/app/pages/queries/hooks/useApiKeyDialog.js
  client/app/pages/queries/hooks/useArchiveQuery.jsx
  client/app/pages/queries/hooks/useAutocompleteFlags.js
  client/app/pages/queries/hooks/useDataSourceSchema.js
  client/app/pages/queries/hooks/useDeleteVisualization.js
  client/app/pages/queries/hooks/useDuplicateQuery.js
  client/app/pages/queries/hooks/useEditScheduleDialog.js
  client/app/pages/queries/hooks/useEditVisualizationDialog.js
  client/app/pages/queries/hooks/useEmbedDialog.js
  client/app/pages/queries/hooks/useFormatQuery.js
  client/app/pages/queries/hooks/usePermissionsEditorDialog.js
  client/app/pages/queries/hooks/usePublishQuery.js
  client/app/pages/queries/hooks/useQuery.js
  client/app/pages/queries/hooks/useQueryDataSources.js
  client/app/pages/queries/hooks/useQueryExecute.js
  client/app/pages/queries/hooks/useQueryFlags.js
  client/app/pages/queries/hooks/useQueryParameters.js
  client/app/pages/queries/hooks/useRenameQuery.js
  client/app/pages/queries/hooks/useUnpublishQuery.js
  client/app/pages/queries/hooks/useUpdateQuery.jsx
  client/app/pages/queries/hooks/useUpdateQueryDescription.js
  client/app/pages/queries/hooks/useUpdateQueryTags.js
  client/app/pages/queries/hooks/useVisualizationTabHandler.js
  client/app/pages/queries/utils/deleteQueryVisualization.js
  client/app/pages/queries/utils/duplicateQuery.js
  client/app/pages/queries/utils/editQueryVisualization.js
  client/app/pages/queries/utils/index.js
Labels: Frontend, Frontend: React

#4504 Migrate Query Source page to React: alerts
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QuerySource.less
  client/app/pages/queries/components/QuerySourceAlerts.jsx
  client/app/pages/queries/components/QuerySourceAlerts.less
Labels: Frontend, Frontend: React

#4505 Migrate Query Source page to React: unsaved changes alert
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/hooks/useUnsavedChangesAlert.js
Labels: Frontend, Frontend: React

#4503 Migrate Query Source to React: resizable areas (v2)
  client/app/assets/less/redash/query.less
  client/app/components/Resizable/index.jsx
  client/app/components/Resizable/index.less
  client/app/components/dashboards/dashboard-grid.less
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QuerySource.less
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4506 Migrate Query pages to React: fix permissions
  client/app/pages/queries/components/QuerySourceAlerts.jsx
  client/app/pages/queries/hooks/useQueryFlags.js
Labels: Frontend, Frontend: React

#4507 Migrate Query Source page to React: don't reload when saving new query
  client/app/pages/queries/hooks/useQuery.js
  client/app/pages/queries/hooks/useUpdateQuery.jsx
Labels: Frontend, Frontend: React

#4498 Fix: properly encode UTF-8 filenames in query results request
  redash/handlers/query_results.py
  tests/handlers/test_query_results.py
Labels: Backend, Bug, Python 3

#4509 Migrate Query pages to React: fix tests
  client/app/components/Parameters.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryViewExecuteButton.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/hooks/useQuery.js
  client/cypress/integration/embed/share_embed_spec.js
  client/cypress/integration/query/create_query_spec.js
  client/cypress/integration/query/parameter_spec.js
  client/cypress/integration/visualizations/edit_visualization_dialog_spec.js
  client/cypress/integration/visualizations/pivot_spec.js
  client/cypress/integration/visualizations/sankey_sunburst_spec.js
  client/cypress/integration/visualizations/table/table_spec.js
Labels: Frontend, Frontend: React

#4516 Fix: don't try to access message property of an exception
  redash/query_runner/google_spreadsheets.py
Labels: Backend, Python 3
