Repository getredash/redash, pull requests merged in 2020-12, with the labels that each got.

#5294 Redesign desktop nav bar
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.less
Labels: Frontend

#5291 Add React Fast Refresh + Hot Module Reloading
  package-lock.json
  package.json
  webpack.config.js
Labels: Frontend

#5303 Remove leftover log from Desktop Navbar
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
Labels: Bug, Frontend

#5299 Sync date format from settings with clientConfig
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/settings/components/GeneralSettings/FormatSettings.jsx
  client/app/pages/settings/hooks/useOrganizationSettings.js
  client/app/services/auth.js
  client/cypress/integration/settings/organization_settings_spec.js
  client/cypress/support/commands.js
  client/cypress/tsconfig.json
  package-lock.json
  package.json
Labels: Frontend

#5305 added eslint no-console
  client/.eslintrc.js
Labels: Frontend

#5318 Obfuscate non-email alert destinations
  redash/destinations/chatwork.py
  redash/destinations/hangoutschat.py
  redash/destinations/hipchat.py
  redash/destinations/mattermost.py
  redash/destinations/pagerduty.py
  redash/destinations/slack.py
  redash/destinations/webhook.py
Labels: Backend

#5304 Dropdown param search fix
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/components/SelectWithVirtualScroll.tsx
  client/cypress/integration/query/parameter_spec.js
Labels: Bug, Frontend
