Repository getredash/redash, pull requests merged in 2020-06, with the labels that each got.

#4952 Make sure queries have options and parameters
  client/app/services/query.js
Labels: Bug, Frontend

#4959 Fix Destination not returning custom error message
  client/app/components/ApplicationArea/ErrorMessage.jsx
  client/app/components/CreateSourceDialog.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/cypress/integration/destination/create_destination_spec.js
  client/cypress/support/redash-api/index.js
Labels: Frontend

#4962 Make sure page updates when 'routes' changes
  client/app/components/ApplicationArea/Router.jsx
Labels: Frontend

#4965 Fix Sankey issue to render 1 and 5 stages
  client/cypress/integration/visualizations/sankey_sunburst_spec.js
  viz-lib/src/visualizations/sankey/d3sankey.js
  viz-lib/src/visualizations/sankey/initSankey.js
Labels: Bug, Frontend

#4859 Vertical navbar
  client/app/assets/less/inc/base.less
  client/app/assets/less/redash/query.less
  client/app/components/ApplicationArea/ApplicationHeader/FavoritesDropdown.jsx
  client/app/components/ApplicationArea/ApplicationHeader/index.jsx
  client/app/components/ApplicationArea/ApplicationHeader/index.less
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.less
  client/app/components/ApplicationArea/ApplicationLayout/MobileNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/MobileNavbar.less
  client/app/components/ApplicationArea/ApplicationLayout/VersionInfo.jsx
  client/app/components/ApplicationArea/ApplicationLayout/index.jsx
  client/app/components/ApplicationArea/ApplicationLayout/index.less
  client/app/components/ApplicationArea/routeWithUserSession.jsx
  client/app/components/PageHeader.jsx
  client/app/components/admin/Layout.jsx
  client/app/components/admin/layout.less
  client/app/pages/alert/AlertEdit.jsx
  client/app/pages/alert/AlertNew.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/alert/components/Title.less
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/DashboardPage.less
  client/app/pages/dashboards/PublicDashboardPage.less
  client/app/pages/dashboards/components/DashboardHeader.less
  client/app/pages/home/Home.less
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/QueryPageHeader.less
  client/cypress/integration/dashboard/dashboard_spec.js
  client/cypress/integration/dashboard/grid_compliant_widgets_spec.js
  client/cypress/integration/dashboard/textbox_spec.js
  client/cypress/integration/query/search_query_spec.js
  client/cypress/integration/user/login_spec.js
  client/cypress/integration/user/logout_spec.js
Labels: Frontend

#4977 Fix headless mode (didn't work with vertical navbar)
  client/app/assets/less/inc/base.less
  client/app/components/ApplicationArea/ApplicationLayout/index.less
  client/app/pages/dashboards/PublicDashboardPage.less
  client/app/pages/queries/VisualizationEmbed.jsx
  client/cypress/integration/user/logout_spec.js
Labels: Bug, Frontend

#4978 Navbar: show correct settings link for non-admin users
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/MobileNavbar.jsx
  client/app/components/SettingsWrapper.jsx
  client/app/services/settingsMenu.js
  client/cypress/integration/settings/settings_tabs_spec.js
  client/cypress/support/redash-api/index.js
Labels: Frontend

#4979 Add/Edit Tags dialog does not set focus on tags input
  client/app/components/tags-control/EditTagsDialog.jsx
Labels: Bug, Frontend

#4976 Add New Dashboard/Query/Alert buttons to corresponding list pages
  client/app/assets/less/inc/base.less
  client/app/components/PageHeader.jsx
  client/app/components/PageHeader/index.jsx
  client/app/components/PageHeader/index.less
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/dashboard-list.css
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries-list/queries-list.css
Labels: Frontend

#4981 ErrorMessage is not centered
  client/app/assets/less/inc/base.less
  client/app/components/ApplicationArea/ErrorMessage.jsx
  client/app/components/ApplicationArea/ErrorMessage.less
Labels: Bug, Frontend

#4989 Fix CLI command for "status"
  redash/cli/__init__.py
Labels: Backend

#4994 Some permissions fixes
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
Labels: Frontend

#4991 Catch QueryResultError on widget load
  client/app/pages/dashboards/hooks/useDashboard.js
Labels: Frontend

#4995 Refactor Organization Settings and add extension points to it
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/settings/components/AuthSettings/GoogleLoginSettings.jsx
  client/app/pages/settings/components/AuthSettings/PasswordLoginSettings.jsx
  client/app/pages/settings/components/AuthSettings/SAMLSettings.jsx
  client/app/pages/settings/components/AuthSettings/index.jsx
  client/app/pages/settings/components/GeneralSettings/BeaconConsentSettings.jsx
  client/app/pages/settings/components/GeneralSettings/FeatureFlagsSettings.jsx
  client/app/pages/settings/components/GeneralSettings/FormatSettings.jsx
  client/app/pages/settings/components/GeneralSettings/PlotlySettings.jsx
  client/app/pages/settings/components/GeneralSettings/index.jsx
  client/app/pages/settings/components/prop-types.js
Labels: Frontend

#4996 Refactor User Profile page and add extension points to it
  client/app/components/users/UserEdit.jsx
  client/app/components/users/UserShow.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/components/ApiKeyForm.jsx
  client/app/pages/users/components/CreateUserDialog.jsx
  client/app/pages/users/components/EditableUserProfile.jsx
  client/app/pages/users/components/PasswordForm/ChangePasswordDialog.jsx
  client/app/pages/users/components/PasswordForm/PasswordLinkAlert.jsx
  client/app/pages/users/components/PasswordForm/PasswordResetForm.jsx
  client/app/pages/users/components/PasswordForm/ResendInvitationForm.jsx
  client/app/pages/users/components/PasswordForm/index.jsx
  client/app/pages/users/components/ReadOnlyUserProfile.jsx
  client/app/pages/users/components/ReadOnlyUserProfile.test.js
  client/app/pages/users/components/ToggleUserForm.jsx
  client/app/pages/users/components/UserGroups.jsx
  client/app/pages/users/components/UserInfoForm.jsx
  client/app/pages/users/components/__snapshots__/ReadOnlyUserProfile.test.js.snap
  client/app/pages/users/hooks/useUserGroups.js
Labels: Frontend

#5000 Allow unregistering settings tabs
  client/app/components/SettingsWrapper.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
  client/app/services/settingsMenu.js
  client/app/services/settingsMenu.test.js
Labels: Frontend

#4998 Dynamically register frontend routes
  client/app/components/ApplicationArea/index.jsx
  client/app/config/index.js
  client/app/index.js
  client/app/pages/admin/Jobs.jsx
  client/app/pages/admin/OutdatedQueries.jsx
  client/app/pages/admin/SystemStatus.jsx
  client/app/pages/alert/Alert.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/PublicDashboardPage.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/home/Home.jsx
  client/app/pages/index.js
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
  client/app/services/routes.js
Labels: Frontend

#5003 Fix org option in users create_root cli command
  redash/cli/users.py
Labels: Backend, Bug

#4990 Remove pace-progress
  client/app/assets/less/main.less
  client/app/config/index.js
  package-lock.json
  package.json
Labels: Frontend

#5007 Too large visualization cause filters block to collapse
  client/app/components/dashboards/dashboard-grid.less
Labels: Bug, Frontend

#5009 Textbox: confirm close if text was changed
  client/app/components/dashboards/TextboxDialog.jsx
Labels: Frontend, UX

#4983 Allow private addresses when enforcing is disabled
  redash/query_runner/__init__.py
Labels: Backend, Bug

#5004 Add "Last 12 months" option to dynamic date ranges
  client/app/components/dynamic-parameters/DateRangeParameter.jsx
  client/app/services/parameters/DateRangeParameter.js
Labels: Frontend
