Repository getredash/redash, pull requests merged in 2020-11, with the labels that each got.

#5221 Multiselect dropdown slowness (fix)
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/components/SelectWithVirtualScroll.tsx
  client/app/lib/calculateTextWidth.ts
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#5255 bugfix: fix #5254
  client/app/components/dashboards/DashboardGrid.jsx
Labels: Bug, Frontend, Visualizations, Visualizations: Table

#5214 Enable graceful shutdown of rq workers
  bin/docker-entrypoint
  redash/tasks/worker.py
Labels: Backend

#5262 Enable Boxplot to be horizontal
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.jsx
Labels: Frontend, Visualizations, Visualizations: Chart

#5259 Frontend updates from internal fork
  Dockerfile
  client/.eslintrc.js
  client/app/assets/images/db-logos/databricks.png
  client/app/assets/less/redash/query.less
  client/app/components/ApplicationArea/ApplicationLayout/index.jsx
  client/app/components/ApplicationArea/ErrorMessage.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/Link.jsx
  client/app/components/UserGroups.jsx
  client/app/components/UserGroups.less
  client/app/components/dynamic-parameters/DynamicButton.less
  client/app/components/dynamic-parameters/DynamicDateRangePicker.jsx
  client/app/components/dynamic-parameters/DynamicParameters.less
  client/app/components/empty-state/EmptyState.d.ts
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/empty-state/empty-state.less
  client/app/components/items-list/components/ItemsTable.jsx
  client/app/components/queries/ApiKeyDialog/index.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/useDatabricksSchema.js
  client/app/lib/queryFormat.test.js
  client/app/lib/queryFormat.ts
  client/app/lib/utils.js
  client/app/pages/alert/AlertEdit.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/home/Home.jsx
  client/app/pages/home/components/FavoritesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QuerySourceAlerts.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/hooks/useAutoLimitFlags.js
  client/app/pages/queries/hooks/useFormatQuery.js
  client/app/pages/queries/hooks/useQuery.js
  client/app/pages/queries/hooks/useQueryFlags.js
  client/app/pages/queries/hooks/useUpdateQuery.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/settings/components/AuthSettings/PasswordLoginSettings.jsx
  client/app/pages/settings/components/AuthSettings/SAMLSettings.jsx
  client/app/pages/settings/components/GeneralSettings/BeaconConsentSettings.jsx
  client/app/pages/settings/components/GeneralSettings/FeatureFlagsSettings.jsx
  client/app/pages/settings/components/GeneralSettings/FormatSettings.jsx
  client/app/pages/settings/components/GeneralSettings/PlotlySettings.jsx
  client/app/pages/settings/components/prop-types.js
  client/app/pages/settings/hooks/useOrganizationSettings.js
  client/app/pages/users/components/ReadOnlyUserProfile.jsx
  client/app/pages/users/components/UserInfoForm.jsx
  client/app/services/dashboard.js
  client/app/services/policy/DefaultPolicy.js
  client/app/services/query.js
  client/cypress/integration/embed/share_embed_spec.js
  package-lock.json
  package.json
  viz-lib/src/visualizations/chart/Renderer/initChart.js
Labels: Frontend

#5277 Remove unwanted props from Select component
  client/app/components/QueryBasedParameterInput.jsx
Labels: Bug, Frontend

#5284 Fix QuerySourceDropdown value type
  client/app/pages/queries/components/QuerySourceDropdown.jsx
  client/app/pages/queries/components/QuerySourceDropdownItem.jsx
Labels: Bug, Frontend

#5287 Changed 'Delete Alert' into 'Delete' for consistency
  client/app/pages/alert/components/MenuButton.jsx
Labels: Frontend
