Repository getredash/redash, pull requests merged in 2020-09, with the labels that each got.

#5140 Add toggle to disable public URLs
  client/app/components/ApplicationArea/routeWithApiKeySession.jsx
  client/app/components/EditVisualizationButton/QueryControlDropdown.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/cypress/integration/dashboard/sharing_spec.js
  client/cypress/integration/embed/share_embed_spec.js
  client/cypress/support/redash-api/index.js
  redash/handlers/authentication.py
  redash/handlers/dashboards.py
  redash/settings/organization.py
Labels: Backend, Frontend

#5139 Antd v4: Fix CreateUserDialog
  client/app/pages/users/components/CreateUserDialog.jsx
  client/cypress/integration/user/create_user_spec.js
Labels: Bug, Frontend

#5136 Move CardsList to typescript
  client/app/components/cards-list/CardsList.jsx
  client/app/components/cards-list/CardsList.tsx
Labels: Frontend

#5146 Keep selected filters when switching visualizations
  client/app/components/dashboards/ExpandedWidgetDialog.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/visualizations/VisualizationRenderer.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
Labels: Bug, Frontend

#5088 Add default limit (1000) to SQL queries
  client/app/components/queries/QueryEditor/AutoLimitCheckbox.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.less
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/hooks/useAutoLimitFlags.js
  client/app/services/query-result.js
  client/app/services/query.js
  redash/handlers/queries.py
  redash/handlers/query_results.py
  redash/models/__init__.py
  redash/query_runner/__init__.py
  redash/query_runner/databricks.py
  redash/tasks/queries/maintenance.py
  redash/utils/__init__.py
  tests/handlers/test_query_results.py
  tests/query_runner/test_basesql_queryrunner.py
  tests/tasks/test_refresh_queries.py
  tests/test_models.py
  tests/utils/test_query_limit.py
Labels: Backend, Frontend

#5142 Allow to clear selected tags on list pages
  client/app/components/TagsList.jsx
  client/app/components/TagsList.less
  client/app/components/TagsList.tsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
Labels: Frontend

#5184 Keep additional URL params when forking a query
  client/app/pages/queries/hooks/useDuplicateQuery.js
Labels: Frontend

#5178 Ask user to log in when session expires
  client/app/services/auth.js
  client/app/services/axios.js
  client/app/services/restoreSession.jsx
Labels: Frontend

#5186 Some Choropleth improvements/refactoring
  client/app/components/visualizations/visualizationComponents.jsx
  client/cypress/integration/visualizations/choropleth_spec.js
  viz-lib/src/lib/referenceCountingCache.js
  viz-lib/src/visualizations/choropleth/Editor/BoundsSettings.jsx
  viz-lib/src/visualizations/choropleth/Editor/ColorsSettings.jsx
  viz-lib/src/visualizations/choropleth/Editor/FormatSettings.jsx
  viz-lib/src/visualizations/choropleth/Editor/GeneralSettings.jsx
  viz-lib/src/visualizations/choropleth/Editor/utils.js
  viz-lib/src/visualizations/choropleth/Renderer/index.jsx
  viz-lib/src/visualizations/choropleth/Renderer/initChoropleth.js
  viz-lib/src/visualizations/choropleth/Renderer/utils.js
  viz-lib/src/visualizations/choropleth/getOptions.js
  viz-lib/src/visualizations/choropleth/hooks/useLoadGeoJson.js
  viz-lib/src/visualizations/choropleth/maps/convert-projection.js
  viz-lib/src/visualizations/choropleth/maps/japan.prefectures.geo.json
  viz-lib/src/visualizations/choropleth/maps/usa-albers.geo.json
  viz-lib/src/visualizations/choropleth/maps/usa.geo.json
Labels: Frontend, Visualizations

#5053 Align Y axes at zero
  viz-lib/src/visualizations/chart/Editor/YAxisSettings.jsx
  viz-lib/src/visualizations/chart/getOptions.js
  viz-lib/src/visualizations/chart/plotly/updateYRanges.js
Labels: Frontend, Visualizations, Visualizations: Chart
