Repository getredash/redash, pull requests merged in 2020-03, with the labels that each got.

#4163 refresh_queries shouldn't break because of a single query having a bad schedule object
  redash/models/__init__.py
  redash/tasks/queries/execution.py
  redash/tasks/queries/maintenance.py
  redash/utils/sentry.py
  tests/tasks/test_queries.py
  tests/test_models.py
Labels: Backend

#4680 Table visualization: Show which columns are being used for search
  client/app/visualizations/table/Renderer.jsx
  client/app/visualizations/table/renderer.less
Labels: Frontend, Visualizations, Visualizations: Table

#4586 Dynamic Form: boolean fields related fixes
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/dynamic-form/dynamicFormHelper.js
Labels: Bug, Frontend

#4710 Update Dashboard and Alert headers with the Query one
  client/app/assets/less/inc/alert.less
  client/app/assets/less/redash/query.less
  client/app/pages/alert/components/Title.jsx
  client/app/pages/alert/components/Title.less
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/DashboardPage.less
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/dashboards/components/DashboardHeader.less
  client/app/pages/queries/components/QueryPageHeader.less
  client/cypress/integration/dashboard/dashboard_spec.js
  client/cypress/integration/dashboard/textbox_spec.js
Labels: Frontend

#4607 Remove `route.resolve` feature
  client/app/components/ApplicationArea/Router.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/wrapQueryPage.jsx
Labels: Frontend, Tech Debt

#4594 Refactor dialog wrapper component
  client/app/components/ApplicationArea/ApplicationHeader/index.jsx
  client/app/components/DialogWrapper.jsx
  client/app/components/Parameters.jsx
  client/app/components/SelectItemsDialog.jsx
  client/app/components/dashboards/AddWidgetDialog.jsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/dashboards/dashboard-widget/TextboxWidget.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/query-snippets/QuerySnippetDialog.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/components/users/CreateUserDialog.jsx
  client/app/components/users/UserEdit.jsx
  client/app/lib/hooks/useSearchResults.js
  client/app/pages/alert/components/AlertDestinations.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/hooks/useAddNewParameterDialog.js
  client/app/pages/queries/hooks/useAddToDashboardDialog.js
  client/app/pages/queries/hooks/useApiKeyDialog.js
  client/app/pages/queries/hooks/useEditScheduleDialog.js
  client/app/pages/queries/hooks/useEditVisualizationDialog.js
  client/app/pages/queries/hooks/useEmbedDialog.js
  client/app/pages/queries/hooks/usePermissionsEditorDialog.js
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/users/UsersList.jsx
Labels: Frontend

#4642 Counter enhancements
  .circleci/config.yml
  client/app/visualizations/counter/Editor/CounterValueOptions.jsx
  client/app/visualizations/counter/Editor/FormatSettings.jsx
  client/app/visualizations/counter/Editor/GeneralSettings.jsx
  client/app/visualizations/counter/Editor/GeneralSettings.test.jsx
  client/app/visualizations/counter/Editor/PrimaryValueSettings.jsx
  client/app/visualizations/counter/Editor/PrimaryValueSettings.test.jsx
  client/app/visualizations/counter/Editor/SecondaryValueSettings.jsx
  client/app/visualizations/counter/Editor/SecondaryValueSettings.test.jsx
  client/app/visualizations/counter/Editor/__snapshots__/GeneralSettings.test.jsx.snap
  client/app/visualizations/counter/Editor/__snapshots__/PrimaryValueSettings.test.jsx.snap
  client/app/visualizations/counter/Editor/__snapshots__/SecondaryValueSettings.test.jsx.snap
  client/app/visualizations/counter/Editor/index.js
  client/app/visualizations/counter/Renderer.jsx
  client/app/visualizations/counter/Renderer.test.jsx
  client/app/visualizations/counter/__snapshots__/Renderer.test.jsx.snap
  client/app/visualizations/counter/counterTypes.js
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/countRows/default.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/maxValue/default.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/maxValue/invalid-column.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/minValue/default.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/minValue/invalid-column.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/default.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/invalid-column.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/negative-row-number.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/positive-row-number.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/wrapped-negative-row-number.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/wrapped-positive-row-number.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/rowValue/zero-row-number.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/sumRows/default.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/sumRows/invalid-column.json
  client/app/visualizations/counter/fixtures/getCounterData/counter-types/unused/default.json
  client/app/visualizations/counter/fixtures/getCounterData/display-and-tooltip-format.json
  client/app/visualizations/counter/fixtures/getCounterData/hide-tooltip.json
  client/app/visualizations/counter/fixtures/getCounterData/primary-secondary-different-types.json
  client/app/visualizations/counter/fixtures/getCounterData/trend-negative.json
  client/app/visualizations/counter/fixtures/getCounterData/trend-positive.json
  client/app/visualizations/counter/fixtures/getCounterData/uses-custom-counter-label.json
  client/app/visualizations/counter/fixtures/getCounterData/uses-custom-number-format.json
  client/app/visualizations/counter/fixtures/getCounterData/uses-default-counter-label.json
  client/app/visualizations/counter/getCounterData.js
  client/app/visualizations/counter/getCounterData.test.js
  client/app/visualizations/counter/getOptions/index.js
  client/app/visualizations/counter/getOptions/v1.js
  client/app/visualizations/counter/getOptions/v2.js
  client/app/visualizations/counter/index.js
  client/app/visualizations/counter/render.less
  client/app/visualizations/counter/utils.js
  client/app/visualizations/counter/utils.test.js
  client/cypress/integration/visualizations/counter_spec.js
Labels: Frontend, Visualizations, Visualizations: Counter

#4726 Dashboard Performance: HtmlContent improvements
  client/app/components/HtmlContent.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
Labels: Frontend

#4729 DOMPurify by default removes 'target' attribute
  client/app/components/HtmlContent.jsx
  client/app/services/sanitize.js
  client/app/services/user.js
  client/app/visualizations/choropleth/Renderer/initChoropleth.js
  client/app/visualizations/map/initMap.js
Labels: Bug, Frontend

#4597 Cohort appearance settings
  client/app/visualizations/cohort/Cornelius.jsx
  client/app/visualizations/cohort/Editor/AppearanceSettings.jsx
  client/app/visualizations/cohort/Editor/ColorsSettings.jsx
  client/app/visualizations/cohort/Editor/ColumnsSettings.jsx
  client/app/visualizations/cohort/Editor/OptionsSettings.jsx
  client/app/visualizations/cohort/Editor/index.js
  client/app/visualizations/cohort/Renderer.jsx
  client/app/visualizations/cohort/getOptions.js
Labels: Frontend, Visualizations

#4737 Fix no button to add query tags
  client/app/pages/queries/components/QueryPageHeader.jsx
Labels: Frontend

#4707 Fix query based param with no results crashing page
  client/app/components/ParameterValueInput.jsx
  client/app/components/QueryBasedParameterInput.jsx
  client/app/services/parameters/QueryBasedDropdownParameter.js
  client/cypress/integration/query/parameter_spec.js
Labels: Frontend

#4765 Sankey diagram should occupy all available area (not just the left part)
  client/app/visualizations/sankey/d3sankey.js
Labels: Frontend, Visualizations
