Repository getredash/redash, pull requests merged in 2020-07, with the labels that each got.

#5013 Fix broken custom JS visualization settings
  client/app/components/visualizations/visualizationComponents.jsx
  viz-lib/src/visualizations/visualizationsSettings.js
Labels: Bug, Frontend

#4966 Python query runner fix
  redash/query_runner/python.py
Labels: Backend

#5010 Databricks custom Schema Browser
  client/app/assets/less/inc/schema-browser.less
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.less
  client/app/components/queries/editor-components/databricks/useDatabricksSchema.js
  client/app/components/queries/editor-components/index.js
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/hooks/useAutocompleteFlags.js
  client/app/pages/queries/hooks/useDataSourceSchema.js
  client/app/services/data-source.js
  client/app/services/databricks-data-source.js
  client/app/services/query-result.js
  redash/handlers/api.py
  redash/handlers/databricks.py
  redash/query_runner/databricks.py
  redash/tasks/databricks.py
Labels: Backend, Frontend

#4992 Allow GET from non-admins on data source resource
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/components/QueryMetadata.jsx
  redash/handlers/data_sources.py
  tests/handlers/test_data_sources.py
Labels: Backend, Frontend

#5017 Add plus between tags to clarify how they are used
  client/app/assets/less/redash/tags-control.less
  client/app/components/NoTaggedObjectsFound.jsx
  client/app/components/tags-control/TagsControl.jsx
Labels: Frontend

#4904 Y-axis autoscale fails when min or max is set
  viz-lib/src/visualizations/chart/Renderer/PlotlyChart.jsx
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-stacking.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-without-legend.json
  viz-lib/src/visualizations/chart/plotly/index.js
  viz-lib/src/visualizations/chart/plotly/prepareLayout.js
  viz-lib/src/visualizations/chart/plotly/updateLayout.js
  viz-lib/src/visualizations/chart/plotly/utils.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#5023 Fix Databricks Schema Browser scrollbar
  client/app/assets/less/inc/schema-browser.less
  client/app/assets/less/redash/query.less
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.less
Labels: Bug, Frontend

#5022 Refactor: extract commonly used pattern into hook
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/lib/hooks/useImmutableCallback.js
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/hooks/useRefreshRateHandler.js
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/queries/components/wrapQueryPage.jsx
  client/app/pages/queries/hooks/useAddNewParameterDialog.js
  client/app/pages/queries/hooks/useApiKeyDialog.js
  client/app/pages/queries/hooks/useArchiveQuery.jsx
  client/app/pages/queries/hooks/useDeleteVisualization.js
  client/app/pages/queries/hooks/useEditVisualizationDialog.js
  client/app/pages/queries/hooks/useFormatQuery.js
  client/app/pages/queries/hooks/useQueryExecute.js
  client/app/pages/queries/hooks/useUpdateQuery.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/components/ApiKeyForm.jsx
  client/app/pages/users/components/ToggleUserForm.jsx
  client/app/pages/users/components/UserInfoForm.jsx
Labels: Frontend, Tech Debt

#5020 Explicitly sort routes to reduce a chance of conflicts
  client/app/pages/alert/Alert.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/services/routes.js
  package-lock.json
  package.json
Labels: Frontend

#4954 Fix: sorting queries by schedule was resulting in a wrong order
  redash/handlers/queries.py
  redash/models/__init__.py
  redash/models/types.py
Labels: Backend

#5037 Query Source: Add Shift+Enter shortcut for query execution
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/pages/queries/QuerySource.jsx
Labels: Frontend

#5024 Fix Schema Browser items height for Firefox
  client/app/assets/less/inc/schema-browser.less
Labels: Bug, Frontend

#5039 Dynamic Form: Make default extra fields state a prop
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/dynamic-form/dynamicFormHelper.js
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/EditDestination.jsx
Labels: Frontend

#5021 Allow to change order of legend items
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.jsx
  viz-lib/src/visualizations/chart/getOptions.js
  viz-lib/src/visualizations/chart/plotly/applyLayoutFixes.js
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-stacking.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-without-legend.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/pie-multiple-series.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/pie-without-annotations.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/pie.json
  viz-lib/src/visualizations/chart/plotly/prepareLayout.js
  viz-lib/src/visualizations/chart/plotly/prepareLayout.test.js
Labels: Frontend, Visualizations, Visualizations: Chart

#5044 Counter is too large on Query View/Source pages
  client/app/components/dashboards/dashboard-grid.less
  viz-lib/src/visualizations/counter/render.less
Labels: Frontend, Visualizations, Visualizations: Counter

#5045 Databricks Schema Browser: Allow eventlet worker instead of RQ
  .circleci/config.yml
  bin/docker-entrypoint
  client/app/services/databricks-data-source.js
  redash/handlers/databricks.py
  redash/query_runner/databricks.py
  redash/tasks/databricks.py
  requirements.txt
Labels: Backend

#1009 Dashboard URL does not show new name when dashboard name is updated
  client/app/components/dashboards/CreateDashboardDialog.jsx
  client/app/components/queries/AddToDashboardDialog.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/home/Home.jsx
  client/app/services/dashboard.js
  client/cypress/integration/dashboard/dashboard_spec.js
  client/cypress/integration/dashboard/dashboard_tags_spec.js
  client/cypress/integration/dashboard/filters_spec.js
  client/cypress/integration/dashboard/grid_compliant_widgets_spec.js
  client/cypress/integration/dashboard/parameter_mapping_spec.js
  client/cypress/integration/dashboard/sharing_spec.js
  client/cypress/integration/dashboard/textbox_spec.js
  client/cypress/integration/dashboard/widget_spec.js
  client/cypress/integration/visualizations/pivot_spec.js
  client/cypress/integration/visualizations/sankey_sunburst_spec.js
  redash/handlers/api.py
  redash/handlers/dashboards.py
  redash/handlers/favorites.py
  redash/models/__init__.py
  redash/serializers/__init__.py
  tests/handlers/test_dashboards.py
Labels: Backend, enhancement, help wanted

#5050 Fix bundle-extensions script to work on recent importlib-resources.
  bin/bundle-extensions
  tests/extensions/redash-dummy/.gitignore
  tests/extensions/redash-dummy/MANIFEST.in
  tests/extensions/redash-dummy/redash_dummy.egg-info/PKG-INFO
  tests/extensions/redash-dummy/redash_dummy.egg-info/SOURCES.txt
  tests/extensions/redash-dummy/redash_dummy.egg-info/entry_points.txt
  tests/extensions/redash-dummy/redash_dummy/__init__.py
  tests/extensions/redash-dummy/redash_dummy/bundle/WideFooter.jsx
  tests/extensions/redash-dummy/redash_dummy/extension.py
  tests/extensions/redash-dummy/redash_dummy/jobs.py
  tests/extensions/redash-dummy/setup.py
  tests/extensions/test_extensions.py
Labels: Backend

#5029 Fix wrong Y-axis range for stacked bar chart
  viz-lib/src/visualizations/chart/Renderer/PlotlyChart.jsx
  viz-lib/src/visualizations/chart/Renderer/initChart.js
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/box-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-single-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-second-axis.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-with-stacking.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareLayout/default-without-legend.json
  viz-lib/src/visualizations/chart/plotly/index.js
  viz-lib/src/visualizations/chart/plotly/prepareLayout.js
  viz-lib/src/visualizations/chart/plotly/updateChartSize.js
  viz-lib/src/visualizations/chart/plotly/updateLayout.js
  viz-lib/src/visualizations/chart/plotly/updateYRanges.js
  viz-lib/src/visualizations/chart/plotly/utils.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#5052 Add Column Type to Databricks schema browser
  client/app/assets/less/inc/schema-browser.less
  client/app/components/queries/QueryEditor/ace.js
  client/app/components/queries/QueryEditor/index.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/services/data-source.js
  redash/models/__init__.py
  redash/query_runner/databricks.py
  redash/query_runner/pg.py
Labels: Backend, Frontend

#5064 Move page size select to the Paginator component
  client/app/components/Paginator.jsx
  client/app/components/groups/DetailsPageSidebar.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/pages/admin/OutdatedQueries.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/users/UsersList.jsx
Labels: Frontend

#5072 Rearrange sidebar menu on Queries List page
  client/app/pages/queries-list/QueriesList.jsx
Labels: Frontend, UX

#5038 Introduce caching to the Databricks Schema Browser
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.less
  client/app/components/queries/editor-components/databricks/useDatabricksSchema.js
  client/app/services/databricks-data-source.js
  redash/handlers/api.py
  redash/handlers/databricks.py
  redash/query_runner/databricks.py
  redash/tasks/databricks.py
  requirements.txt
Labels: Backend, Frontend

#5081 Make sure Policy is loaded for user session
  client/app/components/ApplicationArea/routeWithUserSession.jsx
Labels: Frontend
