Repository getredash/redash, pull requests merged in 2020-05, with the labels that each got.

#4855 Fix: showing current settings tab broken in MULTI_ORG.
  client/app/services/settingsMenu.js
  client/app/services/settingsMenu.test.js
Labels: Frontend

#4854 Fix visualizations with filters not showing selected values
  client/app/components/visualizations/VisualizationRenderer.jsx
  client/app/services/query-result.js
  client/app/visualizations/table/getOptions.js
Labels: Frontend

#4857 Search in navbar works only for first search term
  client/app/components/items-list/components/Sidebar.jsx
  client/app/pages/queries-list/QueriesList.jsx
Labels: Bug, Frontend

#4887 Fix HelpTrigger in header not working
  client/app/components/HelpTrigger.jsx
Labels: Bug, Frontend

#4892 Set the schema item title attribute correctly.
  client/app/pages/queries/components/SchemaBrowser.jsx
Labels: Bug, Frontend

#4907 When resizing chart to a certain size it errors out
  viz-lib/src/visualizations/chart/Renderer/PlotlyChart.jsx
  viz-lib/src/visualizations/chart/plotly/applyLayoutFixes.js
  viz-lib/src/visualizations/chart/plotly/prepareLayout.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#4915 Fix flaky Map (Markers) tests
  client/app/assets/images/fixtures/map-tile.png
  client/cypress/integration/visualizations/choropleth_spec.js
  client/cypress/integration/visualizations/map_spec.js
  viz-lib/src/visualizations/choropleth/Renderer/index.jsx
Labels: Frontend, Visualizations, Visualizations: Map

#4927 Fork button disabled on View Query page for non-admin users
  client/app/pages/queries/QueryView.jsx
Labels: Bug, Frontend

#4922 fix strftime format notation for second and millisecond
  redash/serializers/query_result.py
Labels: Backend
