Repository getredash/redash, pull requests merged in 2020-10, with the labels that each got.

#5196 ScheduleDialog: Filter empty interval groups
  client/app/components/queries/ScheduleDialog.jsx
  client/app/components/queries/__snapshots__/ScheduleDialog.test.js.snap
Labels: Frontend

#5201 Extra actions on Queries and Dashboards pages
  client/app/components/items-list/hooks/useItemsListExtraActions.js
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
Labels: Frontend, enhancement

#5209 Frontend updates from internal fork
  client/.eslintrc.js
  client/app/components/ApplicationArea/ErrorMessage.jsx
  client/app/components/ApplicationArea/ErrorMessageDetails.jsx
  client/app/components/ApplicationArea/handleNavigationIntent.js
  client/app/components/DialogWrapper.d.ts
  client/app/components/HelpTrigger.jsx
  client/app/components/dynamic-parameters/DateParameter.jsx
  client/app/components/dynamic-parameters/DateRangeParameter.jsx
  client/app/components/dynamic-parameters/DynamicButton.jsx
  client/app/components/dynamic-parameters/DynamicDatePicker.jsx
  client/app/components/dynamic-parameters/DynamicDateRangePicker.jsx
  client/app/components/dynamic-parameters/DynamicParameters.less
  client/app/components/empty-state/EmptyState.d.ts
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/empty-state/empty-state.less
  client/app/components/queries/editor-components/databricks/useDatabricksSchema.js
  client/app/index.html
  client/app/lib/utils.js
  client/app/multi_org.html
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/components/DashboardListEmptyState.tsx
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/dashboards/hooks/useDataSources.js
  client/app/pages/home/Home.jsx
  client/app/pages/queries-list/QueriesListEmptyState.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QuerySourceDropdown.jsx
  client/app/pages/queries/components/QuerySourceDropdownItem.jsx
  client/app/pages/queries/components/QuerySourceTypeIcon.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/services/auth.js
  client/app/services/auth.test.js
  client/app/services/notification.d.ts
  client/app/services/parameters/DateRangeParameter.js
  client/cypress/tsconfig.json
  client/tsconfig.json
  viz-lib/src/components/visualizations/editor/ContextHelp.jsx
  viz-lib/src/visualizations/chart/Renderer/PlotlyChart.d.ts
  webpack.config.js
Labels: Frontend

#5154 Add horizontal bar chart
  viz-lib/src/components/visualizations/editor/createTabbedEditor.jsx
  viz-lib/src/visualizations/chart/Editor/ChartTypeSelect.jsx
  viz-lib/src/visualizations/chart/Editor/ColumnMappingSelect.jsx
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.jsx
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.test.js
  viz-lib/src/visualizations/chart/Editor/SeriesSettings.jsx
  viz-lib/src/visualizations/chart/Editor/YAxisSettings.jsx
  viz-lib/src/visualizations/chart/Editor/__snapshots__/GeneralSettings.test.js.snap
  viz-lib/src/visualizations/chart/Editor/index.jsx
  viz-lib/src/visualizations/chart/Renderer/initChart.js
  viz-lib/src/visualizations/chart/plotly/index.js
  viz-lib/src/visualizations/chart/plotly/updateAxes.js
Labels: Frontend, Visualizations, Visualizations: Chart

#5217 Fix Home EmptyState help link
  client/app/components/HelpTrigger.jsx
  client/app/pages/home/Home.jsx
Labels: Bug, Frontend

#5175 Static SAML configuration and assertion encryption
  client/app/pages/settings/components/AuthSettings/SAMLSettings.jsx
  redash/authentication/saml_auth.py
  redash/settings/__init__.py
  redash/settings/organization.py
  requirements.txt
Labels: Backend, Frontend

#5238 Fix dashboard background grid
  client/app/components/dashboards/dashboard-grid.less
Labels: Bug, Frontend

#5231 added required to Form.Item and Input for better UI
  client/app/components/EditParameterSettingsDialog.jsx
Labels: Frontend

#5179 Fix annotation bug causing Oracle queries not to run - ORA-00933
  redash/query_runner/oracle.py
Labels: Backend
