Repository getredash/redash, pull requests merged in 2020-04, with the labels that each got.

#4766 Removing PIP cache from the built image, 300MB size reduction
  Dockerfile
Labels: Backend

#4775 Pie chart ignores series labels
  client/app/visualizations/chart/plotly/preparePieData.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#4752 Upgrade Plotly
  client/app/visualizations/chart/plotly/applyLayoutFixes.js
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/box-single-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/box-with-second-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-single-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-with-second-axis.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-with-stacking.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/default-without-legend.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie-multiple-series.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie-without-annotations.json
  client/app/visualizations/chart/plotly/fixtures/prepareLayout/pie.json
  client/app/visualizations/chart/plotly/prepareLayout.js
  package-lock.json
  package.json
Labels: Frontend, dependencies

#4734 Dashboard Performance: Memoize widgets
  client/app/components/dashboards/DashboardGrid.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
Labels: Frontend

#4736 Fix param added with empty query ignores options
  client/app/services/query.js
Labels: Frontend

#4783 Pie Chart: set contrast colors for text in sectors
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/custom-tooltip.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/default.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/without-labels.json
  client/app/visualizations/chart/plotly/fixtures/prepareData/pie/without-x.json
  client/app/visualizations/chart/plotly/preparePieData.js
Labels: Frontend, Visualizations, Visualizations: Chart

#4770 Table Viz: show 500 records option
  client/app/visualizations/table/Editor/GridSettings.jsx
Labels: Frontend, Visualizations, Visualizations: Table

#4638 Fix comparison error when scale is None
  redash/query_runner/oracle.py
Labels: Backend

#4828 Show explicit user name instead of avatar in lists.
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/queries-list/QueriesList.jsx
Labels: Frontend, UX

#4831 Add column description to table viz
  client/app/visualizations/table/Editor/ColumnEditor.jsx
  client/app/visualizations/table/utils.js
Labels: Frontend, Visualizations, Visualizations: Table

#4793 Visualizations customizable settings
  client/app/components/HelpTrigger.jsx
  client/app/components/QueryLink.jsx
  client/app/components/dashboards/ExpandedWidgetDialog.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/visualizations/EditVisualizationDialog.jsx
  client/app/components/visualizations/EditVisualizationDialog.less
  client/app/components/visualizations/VisualizationName.jsx
  client/app/components/visualizations/VisualizationName.less
  client/app/components/visualizations/VisualizationRenderer.jsx
  client/app/components/visualizations/editor/ContextHelp.jsx
  client/app/components/visualizations/visualizationComponents.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/hooks/useEditVisualizationDialog.js
  client/app/services/widget.js
  client/app/visualizations/Editor.jsx
  client/app/visualizations/Renderer.jsx
  client/app/visualizations/chart/Editor/ChartTypeSelect.jsx
  client/app/visualizations/chart/Renderer/PlotlyChart.jsx
  client/app/visualizations/chart/Renderer/index.jsx
  client/app/visualizations/chart/getOptions.js
  client/app/visualizations/choropleth/Renderer/index.jsx
  client/app/visualizations/details/DetailsRenderer.jsx
  client/app/visualizations/funnel/Renderer/prepareData.js
  client/app/visualizations/index.js
  client/app/visualizations/registeredVisualizations.js
  client/app/visualizations/table/columns/json.jsx
  client/app/visualizations/table/getOptions.js
  client/app/visualizations/visualizationsSettings.js
Labels: Frontend, Visualizations

#4788 Remove Helper Classes from visualizations
  client/app/components/ColorPicker/Swatch.jsx
  client/app/components/ColorPicker/index.jsx
  client/app/components/ColorPicker/index.less
  client/app/components/json-view-interactive/json-view-interactive.less
  client/app/components/visualizations/editor/ContextHelp.jsx
  client/app/components/visualizations/editor/Section.jsx
  client/app/components/visualizations/editor/Section.less
  client/app/components/visualizations/editor/Switch.jsx
  client/app/components/visualizations/editor/Switch.less
  client/app/components/visualizations/editor/TextArea.jsx
  client/app/components/visualizations/editor/TextArea.less
  client/app/components/visualizations/editor/context-help.less
  client/app/components/visualizations/editor/control-label.less
  client/app/components/visualizations/editor/index.js
  client/app/components/visualizations/editor/withControlLabel.jsx
  client/app/visualizations/chart/Editor/AxisSettings.jsx
  client/app/visualizations/chart/Editor/ChartTypeSelect.jsx
  client/app/visualizations/chart/Editor/ColumnMappingSelect.jsx
  client/app/visualizations/chart/Editor/CustomChartSettings.jsx
  client/app/visualizations/chart/Editor/DataLabelsSettings.jsx
  client/app/visualizations/chart/Editor/DefaultColorsSettings.jsx
  client/app/visualizations/chart/Editor/GeneralSettings.jsx
  client/app/visualizations/chart/Editor/HeatmapColorsSettings.jsx
  client/app/visualizations/chart/Editor/PieColorsSettings.jsx
  client/app/visualizations/chart/Editor/SeriesSettings.jsx
  client/app/visualizations/chart/Editor/editor.less
  client/app/visualizations/choropleth/Editor/BoundsSettings.jsx
  client/app/visualizations/choropleth/Editor/ColorsSettings.jsx
  client/app/visualizations/choropleth/Editor/FormatSettings.jsx
  client/app/visualizations/choropleth/Editor/GeneralSettings.jsx
  client/app/visualizations/choropleth/Renderer/Legend.jsx
  client/app/visualizations/choropleth/Renderer/renderer.less
  client/app/visualizations/cohort/Editor/ColorsSettings.jsx
  client/app/visualizations/cohort/Editor/ColumnsSettings.jsx
  client/app/visualizations/cohort/Editor/OptionsSettings.jsx
  client/app/visualizations/cohort/cornelius.less
  client/app/visualizations/cohort/renderer.less
  client/app/visualizations/counter/Editor/FormatSettings.jsx
  client/app/visualizations/counter/Editor/GeneralSettings.jsx
  client/app/visualizations/funnel/Editor/AppearanceSettings.jsx
  client/app/visualizations/funnel/Editor/GeneralSettings.jsx
  client/app/visualizations/map/Editor/FormatSettings.jsx
  client/app/visualizations/map/Editor/GeneralSettings.jsx
  client/app/visualizations/map/Editor/GroupsSettings.jsx
  client/app/visualizations/map/Editor/StyleSettings.jsx
  client/app/visualizations/pivot/renderer.less
  client/app/visualizations/table/Editor/ColumnEditor.jsx
  client/app/visualizations/table/Editor/ColumnsSettings.jsx
  client/app/visualizations/table/Editor/GridSettings.jsx
  client/app/visualizations/table/Editor/editor.less
  client/app/visualizations/table/columns/image.jsx
  client/app/visualizations/table/renderer.less
  client/app/visualizations/variables.less
  client/app/visualizations/word-cloud/Editor.jsx
Labels: Frontend, Visualizations

#4840 Fix dashboard not showing results while refreshing
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
Labels: Bug, Frontend
