Repository getredash/redash, pull requests merged in 2020-01, with the labels that each got.

#4371 Multiprocess RQ workers (using supervisor)
  bin/docker-entrypoint
  docker-compose.yml
  redash/cli/rq.py
  requirements.txt
  worker.conf
Labels: Backend

#4518 Add error boundary to catch errors in visualizations
  client/app/components/ErrorBoundary.jsx
  client/app/visualizations/EditVisualizationDialog.jsx
  client/app/visualizations/VisualizationRenderer.jsx
  client/app/visualizations/chart/Renderer/PlotlyChart.jsx
  client/app/visualizations/funnel/Renderer/prepareData.js
Labels: Frontend

#4502 Replace angular-sanitize with DOMPurify
  client/app/components/HtmlContent.jsx
  client/app/config/index.js
  client/app/services/ng.js
  client/app/services/user.js
  client/app/visualizations/choropleth/Renderer/initChoropleth.js
  client/app/visualizations/map/initMap.js
  package-lock.json
  package.json
Labels: Frontend, Frontend: React

#4551 Add loading state to Query save button
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/pages/queries/QuerySource.jsx
Labels: Frontend

#4563 Tags filter doesn't work because of wrong query params format
  client/app/services/axios.js
  client/cypress/integration/query/parameter_spec.js
  package-lock.json
  package.json
Labels: Bug, Frontend

#4569 Save new query before adding visualization
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/hooks/useAddVisualizationDialog.js
Labels: Frontend

#4573 Fix Map visualization: L.layerGroup cannot compute its bounds
  client/app/visualizations/map/initMap.js
Labels: Bug, Frontend

#4580 Refine Timer and TimeAgo components (get rid of force update)
  client/app/components/TimeAgo.jsx
  client/app/components/Timer.jsx
  client/app/lib/hooks/useForceUpdate.js
Labels: Frontend

#4575 When global dashboard filters enabled, widgets continuously update their local filters
  client/app/visualizations/VisualizationRenderer.jsx
Labels: Bug, Frontend

#4578 Don't allow to fork query while previous fork is still in progress
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/hooks/useDuplicateQuery.js
Labels: Frontend

#4577 Restore query execute notifications (missed during React migration)
  client/app/pages/queries/hooks/useQueryExecute.js
  client/app/services/notifications.js
Labels: Frontend

#4571 Fixes several bugs on dashboard page (see description)
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/PublicDashboardPage.jsx
  client/app/pages/dashboards/components/DashboardListEmptyState.jsx
  client/app/pages/dashboards/components/ShareDashboardDialog.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/dashboards/hooks/useEditModeHandler.js
  client/app/pages/dashboards/hooks/useFullscreenHandler.js
  client/app/pages/dashboards/hooks/useRefreshRateHandler.js
  client/app/pages/queries/components/QueryExecutionStatus.jsx
  client/cypress/integration/query/parameter_spec.js
Labels: Bug, Frontend

#4579 Refine routes definitions
  client/app/components/ApplicationArea/AuthenticatedPageWrapper.jsx
  client/app/components/ApplicationArea/SignedOutPageWrapper.jsx
  client/app/components/ApplicationArea/routeWithApiKeySession.jsx
  client/app/components/ApplicationArea/routeWithUserSession.jsx
  client/app/components/ErrorBoundary.jsx
  client/app/components/items-list/ItemsList.jsx
  client/app/pages/admin/Jobs.jsx
  client/app/pages/admin/OutdatedQueries.jsx
  client/app/pages/admin/SystemStatus.jsx
  client/app/pages/alert/Alert.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/PublicDashboardPage.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/destinations/EditDestination.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/home/Home.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/settings/OrganizationSettings.jsx
  client/app/pages/users/UserProfile.jsx
  client/app/pages/users/UsersList.jsx
Labels: Frontend

#4598 Query editor: fix shortcuts
  client/app/components/queries/QueryEditor/index.jsx
Labels: Bug, Frontend
