Repository getredash/redash, pull requests merged in 2020-08, with the labels that each got.

#4150 Bar chart with second y axis overlaps data series
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareData/bar/default.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareData/bar/normalized.json
  viz-lib/src/visualizations/chart/plotly/fixtures/prepareData/bar/stacked.json
  viz-lib/src/visualizations/chart/plotly/prepareDefaultData.js
Labels: Frontend, Visualizations, Visualizations: Chart

#5103 Make table visualization header fixed
  viz-lib/src/visualizations/table/Renderer.jsx
  viz-lib/src/visualizations/table/renderer.less
Labels: Frontend, Visualizations, Visualizations: Table

#5079 Use Skeleton as ItemsList loading state
  client/app/assets/less/ant.less
  client/app/assets/less/inc/table.less
  client/app/components/items-list/ItemsList.jsx
  client/app/components/items-list/classes/ItemsSource.js
  client/app/components/items-list/components/ItemsTable.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
Labels: Frontend

#5091 Remove content width limit on all pages
  client/app/assets/less/inc/base.less
  client/app/components/layouts/content-with-sidebar.less
  client/app/pages/dashboards/dashboard-list.css
  client/app/pages/queries-list/queries-list.css
Labels: Frontend

#5118 Keep widget loading when fetch request is replaced
  client/app/services/widget.js
Labels: Bug, Frontend

#5122 Introduce Link component
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/MobileNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/VersionInfo.jsx
  client/app/components/BeaconConsent.jsx
  client/app/components/CreateSourceDialog.jsx
  client/app/components/EditVisualizationButton/QueryResultsLink.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/Link.jsx
  client/app/components/PreviewCard.jsx
  client/app/components/QueryLink.jsx
  client/app/components/SettingsWrapper.jsx
  client/app/components/admin/Layout.jsx
  client/app/components/cards-list/CardsList.jsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/components/queries/AddToDashboardDialog.jsx
  client/app/components/visualizations/visualizationComponents.jsx
  client/app/pages/admin/OutdatedQueries.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/alert/components/AlertDestinations.jsx
  client/app/pages/alert/components/Query.jsx
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/PublicDashboardPage.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/home/Home.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries-list/QueriesListEmptyState.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QuerySourceAlerts.jsx
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/components/UserGroups.jsx
  viz-lib/src/lib/value-format.js
  viz-lib/src/lib/value-format.jsx
  viz-lib/src/visualizations/visualizationsSettings.js
Labels: Frontend

#5058 Support multiple queries in a single query box
  redash/query_runner/databricks.py
  tests/query_runner/test_databricks.py
Labels: Backend
