Repository getredash/redash, pull requests merged in 2020-02, with the labels that each got.

#4558 RQ: Missing currently executing queries view
  client/app/components/admin/RQStatus.jsx
  client/app/pages/admin/Jobs.jsx
  redash/monitor.py
  redash/tasks/queries/execution.py
Labels: Backend

#4559 RQ: Keep Job object of query execution for longer period of time
  redash/tasks/queries/execution.py
Labels: Backend

#4595 Sort schema columns alphabetically
  redash/models/__init__.py
  tests/models/test_data_sources.py
Labels: Backend

#4602 Chart editor: enable search in columns selects
  client/app/visualizations/chart/Editor/ColumnMappingSelect.jsx
Labels: Frontend, Visualizations, Visualizations: Chart

#4627 Fix: no need to encode strings anymore
  redash/destinations/email.py
  redash/query_runner/axibase_tsd.py
  redash/query_runner/clickhouse.py
  redash/query_runner/yandex_metrica.py
Labels: Backend, Bug, Feature: Alerts

#4613 Fix dashboard editing permissions not working
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/hooks/useDashboard.js
Labels: Frontend

#4657 Closing the Help Drawer redirects you the homepage
  client/app/components/HelpTrigger.jsx
  client/app/components/HelpTrigger.less
Labels: Bug, Frontend

#4584 Refactor useQueryExecution & add inline query execution status
  client/app/assets/less/redash/query.less
  client/app/components/EditInPlace.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/lib/getQueryResultData.js
  client/app/lib/hooks/useFullscreenHandler.js
  client/app/lib/hooks/useQueryResult.js
  client/app/pages/dashboards/hooks/useDashboard.js
  client/app/pages/queries/QuerySource.jsx
  client/app/pages/queries/QuerySource.less
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/QueryView.less
  client/app/pages/queries/components/QueryExecutionMetadata.jsx
  client/app/pages/queries/components/QueryExecutionMetadata.less
  client/app/pages/queries/components/QueryExecutionStatus.jsx
  client/app/pages/queries/components/QueryMetadata.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/queries/hooks/useQueryExecute.js
  client/app/services/query-result.js
  client/app/visualizations/components/EditVisualizationDialog.jsx
  client/app/visualizations/components/VisualizationRenderer.jsx
Labels: Frontend, UX

#4667 The download button on the dashboard will redirect users to an invalid page
  client/app/components/ApplicationArea/handleNavigationIntent.js
Labels: Bug, Frontend

#4668 Fix Visualization scrollbar in query editor
  client/app/assets/less/redash/query.less
Labels: Bug, Frontend

#4629 Job timeout doesn't kill the mysql query
  redash/query_runner/mysql.py
  redash/tasks/worker.py
Labels: Backend

#4683 Chart with a horizontal legend sometimes doesn't render properly
  client/app/visualizations/chart/plotly/applyLayoutFixes.js
Labels: Bug, Frontend, Visualizations, Visualizations: Chart

#4687 Use main react-grid-layout package instead of fork
  package-lock.json
  package.json
Labels: Frontend

#4689 Change visualization editor scroll to internal divs
  client/app/visualizations/components/EditVisualizationDialog.jsx
  client/app/visualizations/components/EditVisualizationDialog.less
Labels: Frontend

#4574 RQ: reuse same names as before for Docker entrypoints
  bin/docker-entrypoint
Labels: Backend
