Repository getredash/redash, pull requests merged in 2021-03, with the labels that each got.

#5408 Initial a11y improvements
  client/app/assets/less/inc/table.less
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.jsx
  client/app/components/ApplicationArea/ApplicationLayout/DesktopNavbar.less
  client/app/components/FavoritesControl.jsx
  client/app/components/PermissionsEditorDialog/index.jsx
  client/app/components/QuerySelector.jsx
  client/app/components/Resizable/index.jsx
  client/app/components/TagsList.less
  client/app/components/TagsList.tsx
  client/app/components/dynamic-parameters/DynamicButton.jsx
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/components/queries/ApiKeyDialog/index.jsx
  client/app/components/queries/EmbedQueryDialog.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/pages/home/components/FavoritesList.jsx
  client/app/pages/queries/components/QuerySourceDropdownItem.jsx
Labels: Frontend

#5377 Add setting to identify email block domain
  redash/handlers/users.py
  redash/settings/__init__.py
Labels: Backend

#5411 feat: support Trino data-source
  client/app/assets/images/db-logos/trino.png
  redash/query_runner/trino.py
  redash/settings/__init__.py
  requirements_all_ds.txt
Labels: Backend

#5424 Improve icon a11y
  client/app/assets/less/inc/generics.less
  client/app/components/ApplicationArea/ApplicationLayout/VersionInfo.jsx
  client/app/components/ApplicationArea/ErrorMessage.jsx
  client/app/components/BigMessage.jsx
  client/app/components/CreateSourceDialog.jsx
  client/app/components/EmailSettingsWarning.jsx
  client/app/components/FavoritesControl.jsx
  client/app/components/Filters.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/ParameterApplyButton.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/Parameters.jsx
  client/app/components/PermissionsEditorDialog/index.jsx
  client/app/components/QuerySelector.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/components/dashboards/dashboard-widget/Widget.jsx
  client/app/components/dynamic-form/DynamicForm.jsx
  client/app/components/empty-state/EmptyState.jsx
  client/app/components/groups/DetailsPageSidebar.jsx
  client/app/components/groups/ListItemAddon.jsx
  client/app/components/queries/QueryEditor/AutocompleteToggle.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/config/antd-spinner.jsx
  client/app/lib/hooks/useLazyRef.ts
  client/app/lib/hooks/useUniqueId.ts
  client/app/pages/alert/AlertEdit.jsx
  client/app/pages/alert/AlertNew.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/alert/components/AlertDestinations.jsx
  client/app/pages/alert/components/MenuButton.jsx
  client/app/pages/alert/components/NotificationTemplate.jsx
  client/app/pages/alert/components/Query.jsx
  client/app/pages/alert/components/Query.less
  client/app/pages/alerts/AlertsList.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/data-sources/DataSourcesList.jsx
  client/app/pages/data-sources/EditDataSource.jsx
  client/app/pages/destinations/DestinationsList.jsx
  client/app/pages/groups/GroupDataSources.jsx
  client/app/pages/groups/GroupMembers.jsx
  client/app/pages/groups/GroupsList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/queries/QueryView.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/queries/components/QueryPageHeader.jsx
  client/app/pages/queries/components/QueryVisualizationTabs.jsx
  client/app/pages/query-snippets/QuerySnippetsList.jsx
  client/app/pages/users/UsersList.jsx
  client/app/services/restoreSession.jsx
Labels: Frontend

#5434 Adds configuration for `<Tooltip>` trigger on focus
  client/app/components/CodeBlock.jsx
  client/app/components/EmailSettingsWarning.jsx
  client/app/components/HelpTrigger.jsx
  client/app/components/InputWithCopy.jsx
  client/app/components/ParameterApplyButton.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/PermissionsEditorDialog/index.jsx
  client/app/components/TimeAgo.jsx
  client/app/components/Tooltip.tsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/groups/DeleteGroupButton.jsx
  client/app/components/groups/ListItemAddon.jsx
  client/app/components/queries/QueryEditor/AutoLimitCheckbox.jsx
  client/app/components/queries/QueryEditor/AutocompleteToggle.jsx
  client/app/components/queries/QueryEditor/QueryEditorControls.jsx
  client/app/components/queries/SchedulePhrase.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/components/tags-control/TagsControl.jsx
  client/app/pages/alert/AlertView.jsx
  client/app/pages/alert/components/AlertDestinations.jsx
  client/app/pages/alert/components/Query.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/queries/VisualizationEmbed.jsx
  client/app/pages/queries/components/QueryExecutionMetadata.jsx
  client/app/pages/settings/components/AuthSettings/PasswordLoginSettings.jsx
Labels: Frontend

#5439 Add jsx/a11y eslint plugin
  client/.eslintrc.js
  client/app/components/EmailSettingsWarning.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/groups/ListItemAddon.jsx
  package-lock.json
  package.json
Labels: Frontend

#5440 Add live regions to tooltip
  client/app/components/Tooltip.tsx
Labels: Frontend

#5427 Improve input fields a11y
  client/app/components/CreateSourceDialog.jsx
  client/app/components/EditInPlace.jsx
  client/app/components/ParameterMappingInput.jsx
  client/app/components/ParameterValueInput.jsx
  client/app/components/QuerySelector.jsx
  client/app/components/SelectItemsDialog.jsx
  client/app/components/cards-list/CardsList.tsx
  client/app/components/dashboards/CreateDashboardDialog.jsx
  client/app/components/dashboards/TextboxDialog.jsx
  client/app/components/dynamic-parameters/DateParameter.jsx
  client/app/components/groups/CreateGroupDialog.jsx
  client/app/components/items-list/components/Sidebar.jsx
  client/app/components/queries/ApiKeyDialog/index.jsx
  client/app/components/queries/SchemaBrowser.jsx
  client/app/components/queries/editor-components/databricks/DatabricksSchemaBrowser.jsx
  client/app/pages/alert/components/Criteria.jsx
  client/app/pages/alert/components/Criteria.less
  client/app/pages/alert/components/NotificationTemplate.jsx
  client/app/pages/alert/components/Title.jsx
  client/app/pages/dashboards/DashboardList.jsx
  client/app/pages/queries-list/QueriesList.jsx
  client/app/pages/users/UsersList.jsx
  client/app/pages/users/components/PasswordForm/PasswordLinkAlert.jsx
Labels: Frontend

#5450 Get the user's current groups from props instead of useEffect()
  client/app/pages/users/components/UserInfoForm.jsx
Labels: Bug, Frontend
