Repository getredash/redash, pull requests merged in 2021-01, with the labels that each got.

#5314 Add Username and Password fields to MongoDB config
  redash/query_runner/mongodb.py
  tests/query_runner/test_mongodb.py
Labels: Backend

#5312 Secret handling for Yandex, TreasureData, & Postgres/CockroachDB SSL
  redash/query_runner/pg.py
  redash/query_runner/treasuredata.py
  redash/query_runner/yandex_metrica.py
Labels: Backend

#5279 Bar chart e2e test
  client/cypress/integration/visualizations/chart_spec.js
  client/cypress/support/visualizations/chart.js
Labels: Frontend, Visualizations: Chart

#5290 Truncate large Databricks ODBC result sizes
  client/app/lib/useQueryResultData.js
  client/app/pages/queries/components/QueryExecutionMetadata.jsx
  client/app/services/query-result.js
  redash/query_runner/databricks.py
  redash/settings/__init__.py
  redash/settings/helpers.py
Labels: Backend

#5267 Add reorder to dashboard parameter widgets
  client/app/components/Parameters.jsx
  client/app/components/Parameters.less
  client/app/components/dashboards/DashboardGrid.jsx
  client/app/components/dashboards/dashboard-widget/VisualizationWidget.jsx
  client/app/pages/dashboards/DashboardPage.jsx
  client/app/pages/dashboards/components/DashboardHeader.jsx
  client/app/pages/queries/QuerySource.jsx
  client/app/services/dashboard.js
  client/app/services/widget.js
  client/cypress/integration/dashboard/parameter_mapping_spec.js
  client/cypress/integration/dashboard/parameter_spec.js
  client/cypress/integration/query/parameter_spec.js
  client/cypress/support/parameters.js
  migrations/versions/0ec979123ba4_.py
  redash/handlers/dashboards.py
  redash/models/__init__.py
  redash/serializers/__init__.py
  viz-lib/src/components/sortable/index.tsx
Labels: Feature: Dashboards, Frontend

#5286 Fix inconsistent Sankey behavior
  viz-lib/src/visualizations/map/getOptions.ts
  viz-lib/src/visualizations/sankey/Renderer.tsx
  viz-lib/src/visualizations/sankey/d3sankey.ts
  viz-lib/src/visualizations/sankey/index.ts
  viz-lib/src/visualizations/sankey/initSankey.ts
Labels: Bug, Frontend

#5317 Encrypt alert notification destinations
  migrations/versions/d7d747033183_encrypt_alert_destinations.py
  redash/cli/database.py
  redash/models/__init__.py
Labels: Backend

#5349 Fix for Cypress flakiness generated by param_spec
  client/cypress/integration/dashboard/parameter_spec.js
Labels: Bug, Frontend
