Repository getredash/redash, pull requests merged in 2022-07, with the labels that each got.

#5734 Bugfix: Not returning mongodb collection in case Redash can't get a sample data.
  redash/query_runner/mongodb.py
Labels: Team Review

#5280 Configurable mysql datasource
  redash/query_runner/mysql.py
Labels: Backend

#5710 added clear button for query-based parameter inputs
  client/app/components/SelectWithVirtualScroll.tsx
Labels: Team Review

#4697 Add Unarchive button to a dashboard
  client/app/pages/dashboards/components/DashboardHeader.jsx
Labels: Frontend, Feature: Dashboards

#5124 New Query Runner: Arango query runner
  client/app/assets/images/db-logos/arangodb.png
  redash/query_runner/arango.py
  redash/settings/__init__.py
  requirements_all_ds.txt
Labels: Team Review

#5783 fix: increase the default gunicorn timeout
  bin/docker-entrypoint
  docker-compose.yml
Labels: Team Review

#5771 Support for Netezza Performance Server as a data source
  client/app/assets/images/db-logos/nz.png
  redash/query_runner/nz.py
  redash/settings/__init__.py
  requirements.txt
  requirements_all_ds.txt
Labels: Team Review
