Repository getredash/redash, pull requests merged in 2023-08, with the labels that each got.

#5749 Fix python query runner crashing the GUI due to missing 'rows' and/or…
  redash/query_runner/python.py
  tests/query_runner/test_python.py
Labels: 1-week-review

#5702 New cypress test: sorting dashboard list does not crash page.
  client/cypress/integration/dashboard/dashboard_list.js
Labels: Team Review

#5465 add ssl_config to redshift iam class
  redash/query_runner/pg.py
Labels: 1-week-review

#5767 Add Apache ignite Query Runner
  client/app/assets/images/db-logos/ignite.png
  redash/query_runner/ignite.py
  redash/settings/__init__.py
  requirements_all_ds.txt
  tests/query_runner/test_ignite.py
Labels: Team Review

#5198 Fix an issue when using Impala's reserved keywords
  redash/query_runner/impala_ds.py
Labels: Backend, 1-week-review

#5308 sometime,maybe self._profile_image_url is empty string
  redash/models/users.py
Labels: 1-week-review

#5675 Add useQueryAnnotation option to BigQuery Runner
  redash/query_runner/big_query.py
  tests/query_runner/test_bigquery.py
Labels: Team Review

#5602 Fix: Cannot refresh if a query name contain control characters.
  redash/handlers/query_results.py
  requirements.txt
Labels: 1-week-review

#5230 Pass requests metadata to the alerts destionation webhook
  redash/destinations/__init__.py
  redash/destinations/chatwork.py
  redash/destinations/discord.py
  redash/destinations/email.py
  redash/destinations/hangoutschat.py
  redash/destinations/mattermost.py
  redash/destinations/microsoft_teams_webhook.py
  redash/destinations/pagerduty.py
  redash/destinations/slack.py
  redash/destinations/webhook.py
  redash/models/__init__.py
  redash/tasks/alerts.py
  redash/tasks/queries/execution.py
  tests/handlers/test_destinations.py
  tests/tasks/test_alerts.py
Labels: Backend, Team Review

#5723 Query results query parameters
  redash/query_runner/query_results.py
  tests/query_runner/test_query_results.py
Labels: Team Review

#5271 [client] Fix local dev QueryEditor crash when using a data source with "custom" syntax
  client/app/components/ApplicationArea/index.jsx
  client/app/components/queries/QueryEditor/ace.js
Labels: Frontend, javascript, Team Review

#5334 Google Spreadsheet Data Source: support to find a worksheet by title
  redash/query_runner/google_spreadsheets.py
  tests/query_runner/test_google_spreadsheets.py
Labels: Backend, Team Review
