Repository getredash/redash, pull requests merged in 2023-09, with the labels that each got.

#5112 Expire schemas after 7 days
  redash/models/__init__.py
  tests/models/test_data_sources.py
Labels: good first pr

#6115 Add feature: Hide filter components on shared pages
  client/app/components/Parameters.jsx
  client/app/pages/dashboards/components/ShareDashboardDialog.jsx
Labels: Frontend, Feature

#5616 Add Tinybird query runner
  README.md
  client/app/assets/images/db-logos/tinybird.png
  redash/query_runner/clickhouse.py
  redash/query_runner/tinybird.py
  redash/settings/__init__.py
  tests/query_runner/test_tinybird.py
Labels: Team Review

#5860 Check all Trino catalogs if no catalog configured
  redash/query_runner/trino.py
  tests/query_runner/test_trino.py
Labels: Frontend, UX, Bugfix, easy review

#6476 Add Datadog alert destination
  client/app/assets/images/destinations/datadog.png
  redash/destinations/datadog.py
  redash/settings/__init__.py
  tests/handlers/test_destinations.py
Labels: python, Team Review
