Repository getredash/redash, pull requests merged in 2023-07, with the labels that each got.

#6149 update widget_spec.js test to pass on 380 or 381 vizheight
  client/cypress/integration/dashboard/widget_spec.js
Labels: Bugfix, easy review

#6142 Wait for query change to propagate on pivot spec
  client/cypress/integration/visualizations/pivot_spec.js
Labels: Frontend

#6064 chore: inherit BaseSQLQueryRunner in Snowflake query runner
  redash/query_runner/snowflake.py
Labels: Backend, Tech Debt, easy review

#6138 upgrade flask
  redash/app.py
  redash/authentication/__init__.py
  redash/cli/__init__.py
  redash/cli/data_sources.py
  redash/cli/database.py
  redash/cli/groups.py
  redash/cli/organization.py
  redash/cli/queries.py
  redash/cli/users.py
  redash/handlers/base.py
  redash/handlers/static.py
  redash/models/base.py
  redash/models/users.py
  redash/version_check.py
  requirements.txt
  requirements_dev.txt
  tests/__init__.py
  tests/handlers/test_alerts.py
  tests/handlers/test_users.py
  tests/test_authentication.py
  tests/test_cli.py
  tests/test_handlers.py
Labels: dependencies, python

#5788 Install python dependencies one-by-one. Don't exit on failures.
  Dockerfile
Labels: CI

#5849 change the version of greenlet and gevent to fit python 3.10
  requirements.txt
Labels: dependencies, python

#6158 upgrade dev deps
  requirements_dev.txt
Labels: dependencies, python

#6156 add pre-commit
  .pre-commit-config.yaml
  pyproject.toml
  requirements_dev.txt
Labels: CI

#5855 fix(sec): upgrade passlib to 1.7.3
  requirements.txt
Labels: dependencies, python

#5807 Updated vertica-python to 1.1.1
  requirements_all_ds.txt
Labels: dependencies, python

#5812 fix #5811: passing server,port to MS ODBC driver
  redash/query_runner/mssql_odbc.py
Labels: Team Review

#5878 Make the database reencrypt script safer
  redash/cli/database.py
Labels: pre-reboot, ops

#4422 Embed visualizations become flex.
  client/app/assets/less/redash/query.less
Labels: 1-week-review

#5868 Added query runner for Google Analytics Data API (GA4) and Google Search Console API
  client/app/assets/images/db-logos/google_analytics4.png
  client/app/assets/images/db-logos/google_search_console.png
  redash/query_runner/google_analytics4.py
  redash/query_runner/google_search_console.py
  redash/settings/__init__.py
  tests/query_runner/test_google_analytics4.py
  tests/query_runner/test_google_search_console.py
Labels: Backend, Feature: Query Results Data Source, Team Review, pre-reboot

#4254 Give query case sensitive treatment in query hash
  migrations/versions/1038c2174f5d_make_case_insensitive_hash_of_query_text.py
  redash/utils/__init__.py
Labels: 1-week-review

#5996 Add support for a default alert template
  redash/destinations/email.py
  redash/models/__init__.py
  redash/settings/__init__.py
  redash/templates/emails/alert.html
  redash/utils/__init__.py
  tests/models/test_alerts.py
Labels: Frontend, Feature: Alerts, Team Review, easy review

#6195 bump copy-webpack-plugin to 5.1.2
  package.json
  yarn.lock
Labels: Frontend, dependencies

#5865 fix(sec): upgrade httplib2 to 0.19.0
  requirements.txt
Labels: dependencies, python

#6212 bump sentry to 1.28.1
  requirements.txt
Labels: dependencies, python

#6219 bump werkzeug to 2.3.6
  requirements.txt
Labels: dependencies, python

#6106 Feature/Add Discord Alert Destination
  client/app/assets/images/destinations/discord.png
  redash/destinations/discord.py
  redash/settings/__init__.py
  tests/handlers/test_destinations.py
Labels: Feature: Alerts, Feature

#6068 improvement: MongoDB - JSON syntax error sent back to Client
  redash/query_runner/mongodb.py
Labels: Frontend, Feature

#6227 bump PyYaml to 6.0.1
  requirements.txt
Labels: dependencies, python

#4894 Store start datetime in redash:status hash again.
  redash/tasks/queries/maintenance.py
Labels: 1-week-review

#4936 Handle error when data_source is None
  redash/handlers/query_results.py
  tests/handlers/test_query_results.py
Labels: 1-week-review

#5869 [enhancement] Add a CLI command in order to create organization
  redash/cli/organization.py
  tests/test_cli.py
Labels: Backend, pre-reboot

#6254 Bump webpack-dev-server from 3.11.0 to 4.15.1
  package.json
  yarn.lock
Labels: dependencies, javascript

#6258 Bump @pmmmwh/react-refresh-webpack-plugin to 0.5.10, react-refresh to 0.14.0
  package.json
  yarn.lock
Labels: dependencies, javascript

#6259 bump jest to 24.9.0
  yarn.lock
Labels: Frontend, dependencies

#6278 Bump express to 4.18.2
  yarn.lock
Labels: dependencies, javascript

#6303 BigQueryGCE: return project id as not bytes but str
  redash/query_runner/big_query_gce.py
Labels: python, Team Review

#4731 Fixed python query runner and add unittest for python query runner
  tests/query_runner/test_python.py
Labels: Backend, 1-week-review

#2538 MsSql query_runner: Commit the transaction for inserts & Updates
  redash/query_runner/mssql.py
Labels: Backend

#6328 Update package.json so `yarn watch` works again
  package.json
Labels: Frontend

#6329 Webpack-dev-server seems to require the dev-middleware config
  webpack.config.js
Labels: Frontend
